using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using VeloxDev.MVVM;

namespace VeloxDev.AI.Skills;

/// <summary>
/// Bindable status view-model for a single skill. Follows the framework's <c>[VeloxProperty]</c> MVVM
/// conventions; property changes are broadcast by the generator via <see cref="INotifyPropertyChanged"/>
/// and can be bound directly to the UI.
/// <para>
/// <see cref="IsEnabled"/> is deliberately independent of <see cref="State"/>: a skill can be perfectly
/// readable and still be switched off, and switching it off must not unload it. That is the whole point
/// of the toggle — the host (or the agent) decides what reaches the prompt without paying to rediscover
/// anything.
/// </para>
/// </summary>
public partial class SkillStatusViewModel
{
    // Name / Description / State / … / IsEnabled are generated by the generator from the [VeloxProperty]
    // fields below (do not manually declare same-named properties).
    [VeloxProperty] private string name = string.Empty;
    [VeloxProperty] private string description = string.Empty;
    [VeloxProperty] private SkillState state = SkillState.NotStarted;
    [VeloxProperty] private SkillSourceKind source = SkillSourceKind.Embedded;
    [VeloxProperty] private string? path = null;
    [VeloxProperty] private bool isEnabled = true;
    [VeloxProperty] private int resourceCount = 0;
    [VeloxProperty] private string? error = null;

    /// <summary>Readable (its text can be produced).</summary>
    public bool IsReady => State == SkillState.Ready;

    /// <summary>Discovery or read failed (see <see cref="Error"/>).</summary>
    public bool IsError => State == SkillState.Error;

    /// <summary>Contributes to the prompt. Only meaningful together with <see cref="IsReady"/>.</summary>
    public bool IsActive => IsReady && IsEnabled;

    /// <summary>Whether this skill ships bundled resources that can be read on demand.</summary>
    public bool HasResources => ResourceCount > 0;

    /// <summary>Chinese display text for the state (directly usable by UI / Agent).</summary>
    public string StateText => State switch
    {
        SkillState.Ready => "就绪",
        SkillState.Loading => "加载中",
        SkillState.Error => "错误",
        _ => "未发现",
    };

    partial void OnStateChanged(SkillState oldValue, SkillState newValue)
    {
        OnPropertyChanged(nameof(IsReady));
        OnPropertyChanged(nameof(IsError));
        OnPropertyChanged(nameof(IsActive));
        OnPropertyChanged(nameof(StateText));
    }

    partial void OnIsEnabledChanged(bool oldValue, bool newValue)
        => OnPropertyChanged(nameof(IsActive));

    partial void OnResourceCountChanged(int oldValue, int newValue)
        => OnPropertyChanged(nameof(HasResources));
}

/// <summary>
/// An immutable copy of one skill's identity and switch state, safe to read from any thread.
/// </summary>
public sealed class SkillSummary
{
    /// <summary>Skill name.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>One-line description.</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>Which loader produced it — decides how its text is injected.</summary>
    public SkillSourceKind Source { get; set; }

    /// <summary>Readable and switched on.</summary>
    public bool IsActive { get; set; }
}

/// <summary>
/// Globally bindable skill status view-model: the host UI binds <see cref="Skills"/> to list the
/// discovered skills and toggle each one, and reads the aggregate counts. Held by
/// <see cref="SkillScope.Status"/> and rebuilt by <see cref="SkillScope.Refresh"/>.
/// </summary>
public partial class SkillsViewModel
{
    // Skills is generated by the generator from the [VeloxProperty] field below
    // (do not manually declare a same-named property).
    [VeloxProperty] private ObservableCollection<SkillStatusViewModel> skills = [];

    private volatile SkillSummary[] _snapshot = [];

    /// <summary>
    /// Immutable copy of <see cref="Skills"/>, republished on the thread the collection is bound to
    /// whenever a tracked skill changes.
    /// <para>
    /// Read this — not <see cref="Skills"/> — from anywhere that is not the bound thread. An agent
    /// invocation renders its prompt on a thread of the framework's choosing, and enumerating an
    /// <see cref="ObservableCollection{T}"/> there races the host's UI.
    /// </para>
    /// </summary>
    public IReadOnlyList<SkillSummary> Snapshot => _snapshot;

    /// <summary>Number of skills that are readable and switched on.</summary>
    public int ActiveCount => Skills.Count(s => s.IsActive);

    /// <summary>Number of skills that failed to load.</summary>
    public int ErrorCount => Skills.Count(s => s.IsError);

    /// <summary>Whether at least one skill has failed.</summary>
    public bool HasError => ErrorCount > 0;

    /// <summary>
    /// Registers a skill and subscribes to its changes so the aggregates refresh when any skill changes.
    /// </summary>
    public void Track(SkillStatusViewModel skill)
    {
        if (skill is null) return;
        skill.PropertyChanged += OnSkillPropertyChanged;
        Skills.Add(skill);
        NotifyAggregates();
    }

    /// <summary>Removes every tracked skill.</summary>
    public void Reset()
    {
        foreach (var s in Skills)
            s.PropertyChanged -= OnSkillPropertyChanged;
        Skills.Clear();
        NotifyAggregates();
    }

    private void OnSkillPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        // Everything the snapshot carries has to be watched, or a reader could see a stale switch state.
        if (e.PropertyName is nameof(SkillStatusViewModel.State)
            or nameof(SkillStatusViewModel.IsEnabled)
            or nameof(SkillStatusViewModel.Name)
            or nameof(SkillStatusViewModel.Description)
            or nameof(SkillStatusViewModel.Source))
            NotifyAggregates();
    }

    private void NotifyAggregates()
    {
        // Republish here: every mutation of Skills and of a tracked skill's observable fields funnels
        // through this method, and it always runs on the bound thread.
        _snapshot = [.. Skills.Select(s => new SkillSummary
        {
            Name = s.Name,
            Description = s.Description,
            Source = s.Source,
            IsActive = s.IsActive,
        })];

        OnPropertyChanged(nameof(Snapshot));
        OnPropertyChanged(nameof(ActiveCount));
        OnPropertyChanged(nameof(ErrorCount));
        OnPropertyChanged(nameof(HasError));
    }
}
