using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using VeloxDev.Generators.Base;

namespace VeloxDev.Generators.Writers
{
    /// <summary>
    /// Renders one assembly's <see cref="AIContextAssembly"/> into a fragment and its accessors.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The fragment is a directory tree of literal data; the accessors are switches over literal names and casts.
    /// Both are rendered from the same model in one file, so a member cannot appear in one and be missing from
    /// the other.
    /// </para>
    /// <para>
    /// One builder is emitted per directory, each behind its own <c>Lazy</c>, so listing a directory constructs
    /// only that directory. Nothing here walks a subtree to answer a question about its parent.
    /// </para>
    /// </remarks>
    internal static class AIContextTreeWriter
    {
        private const string AIContextNamespace = "VeloxDev.AI";

        /// <summary>One directory, and everything that hangs directly off it.</summary>
        private sealed class DirectoryPlan(string path)
        {
            internal string Path { get; } = path;

            internal int Index { get; set; }

            internal List<DirectoryPlan> Children { get; } = [];

            internal List<AIContextType> TypeEntries { get; } = [];

            internal List<(AIContextType Owner, AIContextMember Member)> MemberNodes { get; } = [];
        }

        internal static string Write(AIContextAssembly assembly, string root, CancellationToken cancellationToken)
        {
            var safeAssembly = Sanitize(assembly.AssemblyName);
            var directories = Plan(assembly, root);

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("#pragma warning disable");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();

            WriteFragment(builder, assembly, safeAssembly, directories);
            builder.AppendLine();
            WriteAccessors(builder, assembly, safeAssembly, cancellationToken);
            builder.AppendLine();
            WriteRegistration(builder, assembly, safeAssembly);

            return builder.ToString();
        }

        // ── 规划 ──

        /// <summary>
        /// Lays the fragment out as directories, breadth-first, and numbers them for the emitted switch.
        /// </summary>
        private static List<DirectoryPlan> Plan(AIContextAssembly assembly, string root)
        {
            var byPath = new Dictionary<string, DirectoryPlan>(System.StringComparer.Ordinal);
            var rootPlan = new DirectoryPlan(root);
            byPath[root] = rootPlan;

            DirectoryPlan EnsurePath(string path)
            {
                if (byPath.TryGetValue(path, out var existing)) return existing;

                var separator = path.LastIndexOf('/');
                var parent = EnsurePath(separator < 0 ? root : path.Substring(0, separator));
                var plan = new DirectoryPlan(path);
                byPath[path] = plan;
                parent.Children.Add(plan);
                return plan;
            }

            foreach (var type in assembly.Types)
            {
                var entryDirectory = EnsurePath(type.Path);

                // 类型条目本身也当目录：它的子节点就是成员目录，这样 FindEntry 与 List 用同一条路径规则。
                foreach (var (directory, members) in SplitMembers(type))
                {
                    var memberDirectory = EnsurePath(entryDirectory.Path + "/" + directory);
                    foreach (var member in members)
                    {
                        memberDirectory.MemberNodes.Add((type, member));
                    }
                }

                var parentPath = type.Path.Substring(0, type.Path.Length - type.FullName.Length - 1);
                EnsurePath(parentPath).TypeEntries.Add(type);
            }

            var ordered = byPath.Values.ToList();
            ordered.Sort(static (a, b) =>
            {
                var depth = Depth(a.Path).CompareTo(Depth(b.Path));
                return depth != 0 ? depth : string.CompareOrdinal(a.Path, b.Path);
            });

            for (var i = 0; i < ordered.Count; i++) ordered[i].Index = i;

            return ordered;
        }

        private static int Depth(string path)
        {
            var depth = 0;
            foreach (var c in path) if (c == '/') depth++;
            return depth;
        }

        /// <summary>
        /// Groups a type's members by the directory each belongs in.
        /// </summary>
        private static IEnumerable<(string Directory, IReadOnlyList<AIContextMember> Members)> SplitMembers(AIContextType type)
        {
            if (type.Kind == AIContextTypeKind.Enum)
            {
                if (type.Members.Count > 0) yield return ("Members", type.Members);
                yield break;
            }

            var groups = new (string Directory, List<AIContextMember> Members)[]
            {
                ("Properties", []),
                ("Fields", []),
                ("Commands", []),
                ("Methods", []),
            };

            foreach (var member in type.Members)
            {
                var index = member.IsMethod ? 3 : member.IsCommand ? 2 : member.IsField ? 1 : 0;
                groups[index].Members.Add(member);
            }

            foreach (var (directory, members) in groups)
            {
                if (members.Count > 0) yield return (directory, members);
            }
        }

        // ── 片段 ──

        private static void WriteFragment(
            StringBuilder builder,
            AIContextAssembly assembly,
            string safeAssembly,
            IReadOnlyList<DirectoryPlan> directories)
        {
            builder.AppendLine($"namespace {AIContextNamespace}.Generated;");
            builder.AppendLine();
            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// The agent context tree fragment contributed by <c>{assembly.AssemblyName}</c>.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine($"internal sealed class {safeAssembly}_AIContextFragment : global::{AIContextNamespace}.AIContextFragment");
            builder.AppendLine("{");
            builder.AppendLine($"    public override string AssemblyName => \"{Escape(assembly.AssemblyName)}\";");
            builder.AppendLine();

            builder.AppendLine("    private static readonly string[] _directories =");
            builder.AppendLine("    [");
            foreach (var directory in directories)
            {
                builder.AppendLine($"        \"{Escape(directory.Path)}\",");
            }
            builder.AppendLine("    ];");
            builder.AppendLine("    public override global::System.Collections.Generic.IReadOnlyList<string> DirectoryPaths => _directories;");
            builder.AppendLine();

            builder.AppendLine("    private static readonly string[] _typeNames =");
            builder.AppendLine("    [");
            foreach (var type in assembly.Types)
            {
                builder.AppendLine($"        \"{Escape(type.FullName)}\",");
            }
            builder.AppendLine("    ];");
            builder.AppendLine("    private static readonly string[] _typePaths =");
            builder.AppendLine("    [");
            foreach (var type in assembly.Types)
            {
                builder.AppendLine($"        \"{Escape(type.Path)}\",");
            }
            builder.AppendLine("    ];");
            builder.AppendLine("    public override global::System.Collections.Generic.IReadOnlyList<string> TypeNames => _typeNames;");
            builder.AppendLine("    public override global::System.Collections.Generic.IReadOnlyList<string> TypePaths => _typePaths;");
            builder.AppendLine();

            builder.AppendLine("    private static readonly global::VeloxDev.AI.AIContextNode[] _empty = [];");
            builder.AppendLine("    private static readonly global::System.Lazy<global::VeloxDev.AI.AIContextNode[]>[] _slots =");
            builder.AppendLine("    [");
            foreach (var directory in directories)
            {
                builder.AppendLine($"        new(static () => Build{directory.Index}(), global::System.Threading.LazyThreadSafetyMode.ExecutionAndPublication),");
            }
            builder.AppendLine("    ];");
            builder.AppendLine();

            builder.AppendLine("    public override global::System.Collections.Generic.IReadOnlyList<global::VeloxDev.AI.AIContextNode> ChildrenOf(string directoryPath)");
            builder.AppendLine("    {");
            builder.AppendLine("        switch (directoryPath)");
            builder.AppendLine("        {");
            foreach (var directory in directories)
            {
                builder.AppendLine($"            case \"{Escape(directory.Path)}\": return _slots[{directory.Index}].Value;");
            }
            builder.AppendLine("            default: return _empty;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");

            foreach (var directory in directories)
            {
                builder.AppendLine();
                WriteDirectoryBuilder(builder, directory);
            }

            builder.AppendLine("}");
        }

        private static void WriteDirectoryBuilder(StringBuilder builder, DirectoryPlan directory)
        {
            builder.AppendLine($"    private static global::VeloxDev.AI.AIContextNode[] Build{directory.Index}()");
            builder.AppendLine("        =>");
            builder.AppendLine("    [");

            // 类型条目自己就是它那个子节点 —— 不能再出一个同名的 Directory 占位，否则同一个目录里
            // 两个节点同名，查表时只会剩一个（而且剩哪个取决于去重方向）。
            var typePaths = new HashSet<string>(
                directory.TypeEntries.Select(static t => t.Path),
                System.StringComparer.Ordinal);

            foreach (var child in directory.Children.OrderBy(static c => c.Path, System.StringComparer.Ordinal))
            {
                if (typePaths.Contains(child.Path)) continue;

                builder.AppendLine($"        new global::VeloxDev.AI.AIContextNode(\"{Escape(LastSegment(child.Path))}\", global::VeloxDev.AI.AIContextNodeKind.Directory),");
            }

            foreach (var type in directory.TypeEntries.OrderBy(static t => t.FullName, System.StringComparer.Ordinal))
            {
                builder.AppendLine($"        {RenderTypeNode(type)},");
            }

            foreach (var (owner, member) in directory.MemberNodes)
            {
                builder.AppendLine($"        {RenderMemberNode(owner, member)},");
            }

            builder.AppendLine("    ];");
        }

        private static string RenderTypeNode(AIContextType type)
        {
            var kind = type.Kind switch
            {
                AIContextTypeKind.Enum => "EnumType",
                AIContextTypeKind.Interface => "InterfaceType",
                AIContextTypeKind.Component => "ComponentType",
                _ => "DataType",
            };

            // 框架侧还是客户侧由路径前缀决定（Framework/ 与 Customer/），不需要再记一个标志。
            // 值类型是目录要额外记的一条：`DataType` 把 struct 与 class 收在一起，而 schema 要分开报。
            var flags = type.Symbol.TypeKind == TypeKind.Struct
                ? "global::VeloxDev.AI.AIContextFlags.IsValueType"
                : "global::VeloxDev.AI.AIContextFlags.None";

            return $"new global::VeloxDev.AI.AIContextNode(\"{Escape(type.FullName)}\", "
                 + $"global::VeloxDev.AI.AIContextNodeKind.{kind}, "
                 + $"\"{Escape(type.FullName)}\", null, {flags}, 0, "
                 + $"{RenderTexts(type.Descriptions)}, {RenderTypeRefs(type)}, null)";
        }

        /// <summary>
        /// The named types a type entry points at: its base interfaces, and — for an enum — its underlying type.
        /// </summary>
        /// <remarks>
        /// Both are facts the rendered tables print but that a node otherwise has no home for; they ride on the
        /// reference machinery rather than widening the node with two one-off fields.
        /// </remarks>
        private static string RenderTypeRefs(AIContextType type)
        {
            var parts = new List<string>();

            foreach (var name in type.BaseInterfaceNames)
            {
                parts.Add($"new global::VeloxDev.AI.AIContextRef(global::VeloxDev.AI.AIContextRefKind.BaseInterface, \"\", \"{Escape(name)}\")");
            }

            if (type.EnumUnderlyingType is not null)
            {
                parts.Add($"new global::VeloxDev.AI.AIContextRef(global::VeloxDev.AI.AIContextRefKind.MemberType, \"\", \"{Escape(type.EnumUnderlyingType)}\")");
            }

            // 基类型只在树里能找到时才给路径；找不到（比如它的程序集没有分片）就只留名字，
            // 渲染器据此知道「还有一层，但这一层不在目录里」。
            if (type.BaseTypeName is not null)
            {
                parts.Add($"new global::VeloxDev.AI.AIContextRef(global::VeloxDev.AI.AIContextRefKind.BaseType, \"\", \"{Escape(type.BaseTypeName)}\")");
            }

            return parts.Count == 0 ? "null" : "[" + string.Join(", ", parts) + "]";
        }

        private static string RenderMemberNode(AIContextType owner, AIContextMember member)
        {
            var kind = member.IsMethod ? "Method"
                     : member.IsCommand ? "Command"
                     : owner.Kind == AIContextTypeKind.Enum ? "EnumMember"
                     : member.IsField ? "Field"
                     : "Property";

            var flags = new List<string>();
            if (member.CanRead) flags.Add("CanRead");
            if (member.CanWrite) flags.Add("CanWrite");
            if (member.IsStatic) flags.Add("Static");
            if (member.IsCommand) flags.Add("IsCommand");
            if (member.HasVeloxProperty) flags.Add("HasVeloxProperty");
            if (member.HasVeloxCommand) flags.Add("HasVeloxCommand");
            if (member.HasSlotSelectors) flags.Add("HasSlotSelectors");
            if (member.IsPromotedField) flags.Add("IsPromotedField");
            if (member.IsSlotEnumerator) flags.Add("IsSlotEnumerator");
            if (member.IsSingleSlot) flags.Add("IsSingleSlot");
            if (member.IsSlotCollection) flags.Add("IsSlotCollection");

            var flagText = flags.Count == 0
                ? "global::VeloxDev.AI.AIContextFlags.None"
                : string.Join(" | ", flags.Select(static f => $"global::VeloxDev.AI.AIContextFlags.{f}"));

            return $"new global::VeloxDev.AI.AIContextNode(\"{Escape(member.Name)}\", "
                 + $"global::VeloxDev.AI.AIContextNodeKind.{kind}, "
                 + $"\"{Escape(member.DeclaredType)}\", \"{Escape(owner.FullName)}\", {flagText}, {member.Ordinal}, "
                 + $"{RenderTexts(member.Descriptions)}, {RenderMemberRefs(member)}, {RenderParameterNodes(member)})";
        }

        /// <summary>The named types a member points at: its slot selectors, and a command's parameter type.</summary>
        private static string RenderMemberRefs(AIContextMember member)
        {
            var parts = new List<string>();

            foreach (var name in member.SlotSelectorNames)
            {
                parts.Add($"new global::VeloxDev.AI.AIContextRef(global::VeloxDev.AI.AIContextRefKind.SlotSelectorType, \"\", \"{Escape(name)}\")");
            }

            if (member.CommandParameterTypeName is not null)
            {
                parts.Add($"new global::VeloxDev.AI.AIContextRef(global::VeloxDev.AI.AIContextRefKind.CommandParameterType, \"\", \"{Escape(member.CommandParameterTypeName)}\")");
            }

            return parts.Count == 0 ? "null" : "[" + string.Join(", ", parts) + "]";
        }

        private static string RenderParameterNodes(AIContextMember member)
        {
            if (member.Parameters.Count == 0) return "null";

            var parts = member.Parameters.Select(p =>
                $"new global::VeloxDev.AI.AIContextNode(\"{Escape(p.Name)}\", global::VeloxDev.AI.AIContextNodeKind.Parameter, "
                + $"\"{Escape(p.DeclaredType)}\", null, "
                + (p.IsOptional ? "global::VeloxDev.AI.AIContextFlags.Optional" : "global::VeloxDev.AI.AIContextFlags.None")
                + ", 0, null, null, null)");

            return "[" + string.Join(", ", parts) + "]";
        }

        private static string RenderTexts(IReadOnlyList<AIContextText> texts)
        {
            if (texts.Count == 0) return "null";

            var parts = texts.Select(t =>
                $"new global::VeloxDev.AI.AgentText((global::VeloxDev.AI.AgentLanguages){t.Language}, \"{Escape(t.Text)}\")");

            return "[" + string.Join(", ", parts) + "]";
        }

        // ── 访问器 ──

        private static void WriteAccessors(StringBuilder builder, AIContextAssembly assembly, string safeAssembly, CancellationToken cancellationToken)
        {
            for (var i = 0; i < assembly.Types.Count; i++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                WriteAccessor(builder, assembly.Types[i], safeAssembly, i);
                builder.AppendLine();
            }
        }

        private static void WriteAccessor(StringBuilder builder, AIContextType type, string safeAssembly, int index)
        {
            var fullType = FullTypeOf(type.Symbol);

            // 值类型恒有无参构造（`new Anchor()` 合法），但它进不了 `object Create()` 的只有 ref struct。
            var canCreate = type.Symbol.TypeKind switch
            {
                TypeKind.Struct => !type.Symbol.IsRefLikeType,
                TypeKind.Class => !type.Symbol.IsAbstract
                                  && type.Symbol.InstanceConstructors.Any(static c =>
                                         c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public),
                _ => false,
            };

            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Acts on <c>{Escape(type.FullName)}</c> without reflection.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine($"internal sealed class {safeAssembly}_Accessor{index} : global::{AIContextNamespace}.IAIContextAccessor");
            builder.AppendLine("{");
            builder.AppendLine($"    public string TypeName => \"{Escape(type.FullName)}\";");
            builder.AppendLine($"    public global::System.Type TargetType => typeof({fullType});");
            builder.AppendLine($"    public bool HasPublicParameterlessConstructor => {(canCreate ? "true" : "false")};");
            builder.AppendLine();

            builder.AppendLine("    public object Create()");
            builder.AppendLine("    {");
            builder.AppendLine(canCreate
                ? $"        return new {fullType}();"
                : $"        throw new global::System.InvalidOperationException(\"{Escape(type.FullName)} cannot be constructed with no arguments.\");");
            builder.AppendLine("    }");
            builder.AppendLine();

            WriteMemberTypes(builder, type);
            builder.AppendLine();
            WriteTryGet(builder, type, fullType);
            builder.AppendLine();
            WriteSet(builder, type, fullType);
            builder.AppendLine();
            WriteTryExecuteCommand(builder, type, fullType);
            builder.AppendLine();
            WriteCanExecuteCommand(builder, type, fullType);
            builder.AppendLine();
            WriteTryInvoke(builder, type, fullType);
            builder.AppendLine();
            WriteCopyScalarFrom(builder, type, fullType);

            builder.AppendLine("}");
        }

        /// <summary>
        /// Emits the two <c>typeof</c> lookups: a member's declared type, and a command's parameter type.
        /// </summary>
        /// <remarks>
        /// These are the only places a <see cref="System.Type"/> leaves the accessor, and every one of them is a
        /// literal — which is the whole point: a caller that needs a type to hand to a serializer or to close a
        /// generic call gets one the trimmer already rooted, instead of reflecting for it.
        /// </remarks>
        private static void WriteMemberTypes(StringBuilder builder, AIContextType type)
        {
            builder.AppendLine("    public global::System.Type? MemberType(string member)");
            builder.AppendLine("    {");
            builder.AppendLine("        switch (member)");
            builder.AppendLine("        {");

            // 同名成员只出一个 case（提升字段与声明属性可能同名），否则 switch 撞出重复标签。
            var emitted = new HashSet<string>(System.StringComparer.Ordinal);

            foreach (var member in type.Members)
            {
                if (member.IsMethod || !emitted.Add(member.Name)) continue;

                builder.AppendLine($"            case \"{Escape(member.Name)}\": return typeof({MemberTypeOf(member)});");
            }

            builder.AppendLine("            default: return null;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine();

            builder.AppendLine("    public global::System.Type? ParameterType(string commandName)");
            builder.AppendLine("    {");
            builder.AppendLine("        switch (commandName)");
            builder.AppendLine("        {");

            var emittedCommands = new HashSet<string>(System.StringComparer.Ordinal);

            foreach (var member in type.Members)
            {
                if (member.CommandParameterTypeSymbol is null || !emittedCommands.Add(member.Name)) continue;

                builder.AppendLine($"            case \"{Escape(member.Name)}\": return typeof({FullTypeOf(member.CommandParameterTypeSymbol)});");
            }

            builder.AppendLine("            default: return null;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
        }

        /// <summary>The type a member is exposed as, for its <c>typeof</c> literal.</summary>
        private static string MemberTypeOf(AIContextMember member)
            // 由 [VeloxCommand] 方法提升出来的命令：成员上那个类型是方法的返回类型，属性上的是命令接口。
            => member.Symbol is IMethodSymbol
                ? "global::VeloxDev.MVVM.IVeloxCommand"
                : FullTypeOf(member.DeclaredTypeSymbol);

        private static void WriteTryGet(StringBuilder builder, AIContextType type, string fullType)
        {
            builder.AppendLine("    public bool TryGet(object target, string member, out object? value)");
            builder.AppendLine("    {");
            builder.AppendLine($"        var t = ({fullType})target;");
            builder.AppendLine("        switch (member)");
            builder.AppendLine("        {");

            foreach (var member in type.Members)
            {
                // 静态成员没有实例面：`t.X` 编不过（CS0176），而访问器只对实例做事。
                if (member.IsMethod || !member.CanRead || member.IsStatic) continue;
                builder.AppendLine($"            case \"{Escape(member.Name)}\": value = t.{member.Name}; return true;");
            }

            builder.AppendLine("            default: value = null; return false;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
        }

        private static void WriteSet(StringBuilder builder, AIContextType type, string fullType)
        {
            builder.AppendLine("    public string? Set(object target, string member, object? value)");
            builder.AppendLine("    {");
            builder.AppendLine($"        var t = ({fullType})target;");
            builder.AppendLine("        try");
            builder.AppendLine("        {");
            builder.AppendLine("            switch (member)");
            builder.AppendLine("            {");

            foreach (var member in type.Members)
            {
                if (member.IsMethod || !member.CanWrite || member.IsStatic) continue;
                var conversion = RenderConversion(member.DeclaredTypeSymbol, "value");

                builder.AppendLine($"                case \"{Escape(member.Name)}\": t.{member.Name} = {conversion}; return null;");
            }

            builder.AppendLine($"                default: return \"Property '\" + member + \"' is not agent-patchable on {Escape(type.FullName)}.\";");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("        catch (global::System.Exception ex)");
            builder.AppendLine("        {");
            builder.AppendLine($"            return \"Cannot write '\" + member + \"' on {Escape(type.FullName)}: \" + ex.Message;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
        }

        private static void WriteTryExecuteCommand(StringBuilder builder, AIContextType type, string fullType)
        {
            builder.AppendLine("    public bool TryExecuteCommand(object target, string commandName, object? parameter, out string? error)");
            builder.AppendLine("    {");
            builder.AppendLine($"        var t = ({fullType})target;");
            builder.AppendLine("        switch (commandName)");
            builder.AppendLine("        {");

            foreach (var member in type.Members.Where(static m => m.IsCommand))
            {
                // 不查 CanExecute：它只被报告，从不被拦 —— 要拦由工具层自己拦。
                builder.AppendLine($"            case \"{Escape(member.Name)}\":");
                builder.AppendLine("            {");
                builder.AppendLine($"                if (t.{member.Name} is not global::System.Windows.Input.ICommand c) {{ error = \"{Escape(member.Name)} is null.\"; return false; }}");
                builder.AppendLine("                c.Execute(parameter);");
                builder.AppendLine("                error = null;");
                builder.AppendLine("                return true;");
                builder.AppendLine("            }");
            }

            builder.AppendLine($"            default: error = \"Command '\" + commandName + \"' is not registered on {Escape(type.FullName)}.\"; return false;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
        }

        private static void WriteCanExecuteCommand(StringBuilder builder, AIContextType type, string fullType)
        {
            builder.AppendLine("    public bool CanExecuteCommand(object target, string commandName, object? parameter)");
            builder.AppendLine("    {");
            builder.AppendLine($"        var t = ({fullType})target;");
            builder.AppendLine("        switch (commandName)");
            builder.AppendLine("        {");

            foreach (var member in type.Members.Where(static m => m.IsCommand))
            {
                // 每个 case 各起一个作用域：模式变量 `c` 否则会在同一个 switch 里撞名（CS0128）。
                builder.AppendLine($"            case \"{Escape(member.Name)}\":");
                builder.AppendLine("            {");
                builder.AppendLine($"                return t.{member.Name} is global::System.Windows.Input.ICommand command && command.CanExecute(parameter);");
                builder.AppendLine("            }");
            }

            builder.AppendLine("            default: return false;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
        }

        private static void WriteTryInvoke(StringBuilder builder, AIContextType type, string fullType)
        {
            builder.AppendLine("    public bool TryInvoke(object target, string method, object?[] args, out object? returnValue, out string? error)");
            builder.AppendLine("    {");
            builder.AppendLine($"        var t = ({fullType})target;");
            builder.AppendLine("        switch (method)");
            builder.AppendLine("        {");

            // 重载共用一个 case 标签 —— 按名字分组，组内再按实参个数分派。
            // 直接一个重载一个 case 会撞出重复标签（CS0152），而重名方法在 Core 里很常见。
            var byName = type.Members
                .Where(static m => m.IsMethod)
                .GroupBy(static m => m.Name, System.StringComparer.Ordinal)
                .OrderBy(static g => g.Key, System.StringComparer.Ordinal);

            foreach (var group in byName)
            {
                builder.AppendLine($"            case \"{Escape(group.Key)}\":");
                builder.AppendLine("            {");
                builder.AppendLine("                switch (args.Length)");
                builder.AppendLine("                {");

                foreach (var entry in ArityPlan(group.ToList()))
                {
                    builder.AppendLine($"                    case {entry.Key}:");
                    builder.AppendLine("                    {");
                    WriteInvokeBody(builder, type, entry.Value.Member, "                        ", entry.Value.Arity);
                    builder.AppendLine("                    }");
                }

                builder.AppendLine("                    default: break;");
                builder.AppendLine("                }");
                builder.AppendLine("                break;");
                builder.AppendLine("            }");
            }

            builder.AppendLine("            default: break;");
            builder.AppendLine("        }");
            builder.AppendLine($"        returnValue = null; error = \"No overload of '\" + method + \"' on {Escape(type.FullName)} matches \" + args.Length + \" argument(s).\"; return false;");
            builder.AppendLine("    }");
        }

        /// <summary>
        /// Which overload serves which argument count, given that trailing optional parameters may be omitted.
        /// </summary>
        /// <remarks>
        /// The call the accessor emits simply leaves the omitted arguments out: C# then supplies each parameter's
        /// own default, so nothing here has to know what those defaults are.
        /// </remarks>
        private static SortedDictionary<int, (AIContextMember Member, int Arity)> ArityPlan(IReadOnlyList<AIContextMember> overloads)
        {
            var plan = new SortedDictionary<int, (AIContextMember Member, int Arity)>();

            // 实参给全的那个重载先占住自己的个数，同元数的重载本来就分不开（旧实现取反射枚举到的第一个）。
            foreach (var overload in overloads)
            {
                if (!plan.ContainsKey(overload.Parameters.Count))
                {
                    plan[overload.Parameters.Count] = (overload, overload.Parameters.Count);
                }
            }

            // 剩下的个数交给「必填数 ≤ 个数 < 总数」的那个重载；尾部缺的由编译器取默认值。
            foreach (var overload in overloads)
            {
                var required = overload.Parameters.Count(static p => !p.IsOptional);
                for (var arity = required; arity < overload.Parameters.Count; arity++)
                {
                    if (!plan.ContainsKey(arity)) plan[arity] = (overload, arity);
                }
            }

            return plan;
        }

        /// <summary>
        /// Emits one overload's invocation: convert the arguments, call, and turn a failure into a message.
        /// </summary>
        /// <param name="arity">How many arguments the caller supplied — the rest are left to the compiler.</param>
        private static void WriteInvokeBody(StringBuilder builder, AIContextType type, AIContextMember member, string indent, int arity)
        {
            var arguments = new List<string>();
            var writeBack = new List<string>();

            for (var i = 0; i < arity && i < member.Parameters.Count; i++)
            {
                var parameter = member.Parameters[i];

                if (parameter.NeedsLocal)
                {
                    // 局部变量必须声明成参数自己的类型：`out object` 传给 `out IWorkflowSlotViewModel?` 编不过。
                    var parameterType = FullTypeOf(parameter.DeclaredTypeSymbol);
                    var keyword = parameter.RefKind == RefKind.Out ? "out" : "ref";
                    var initial = parameter.RefKind == RefKind.Out ? "default!" : $"({parameterType})args[{i}]!";

                    builder.AppendLine($"{indent}{parameterType} byref{i} = {initial};");
                    arguments.Add($"{keyword} byref{i}");
                    writeBack.Add($"args[{i}] = byref{i};");
                    continue;
                }

                arguments.Add(RenderConversion(parameter.DeclaredTypeSymbol, $"args[{i}]"));
            }

            var call = $"t.{member.Name}({string.Join(", ", arguments)})";

            builder.AppendLine($"{indent}try");
            builder.AppendLine($"{indent}{{");
            builder.AppendLine(member.ReturnsVoid ? $"{indent}    {call};" : $"{indent}    returnValue = {call};");
            foreach (var line in writeBack) builder.AppendLine($"{indent}    {line}");
            if (member.ReturnsVoid) builder.AppendLine($"{indent}    returnValue = null;");
            builder.AppendLine($"{indent}}}");
            builder.AppendLine($"{indent}catch (global::System.Exception ex)");
            builder.AppendLine($"{indent}{{");
            builder.AppendLine($"{indent}    returnValue = null; error = \"Calling '\" + method + \"' on {Escape(type.FullName)} failed: \" + ex.Message; return false;");
            builder.AppendLine($"{indent}}}");
            builder.AppendLine($"{indent}error = null;");
            builder.AppendLine($"{indent}return true;");
        }

        private static void WriteCopyScalarFrom(StringBuilder builder, AIContextType type, string fullType)
        {
            builder.AppendLine("    public int CopyScalarFrom(object source, object target)");
            builder.AppendLine("    {");
            builder.AppendLine("        var from = global::VeloxDev.AI.AIContextTreeRegistry.FindAccessor(source);");
            builder.AppendLine("        if (from is null) return 0;");
            builder.AppendLine();
            builder.AppendLine($"        var to = ({fullType})target;");
            builder.AppendLine("        var copied = 0;");

            foreach (var member in type.Members)
            {
                if (member.IsMethod || !member.CanWrite) continue;
                var conversion = RenderConversion(member.DeclaredTypeSymbol, "value");

                builder.AppendLine("        {");
                builder.AppendLine($"            if (from.TryGet(source, \"{Escape(member.Name)}\", out var value))");
                builder.AppendLine("            {");
                builder.AppendLine("                try");
                builder.AppendLine("                {");
                builder.AppendLine($"                    to.{member.Name} = {conversion};");
                builder.AppendLine("                    copied++;");
                builder.AppendLine("                }");
                builder.AppendLine("                catch { }");
                builder.AppendLine("            }");
                builder.AppendLine("        }");
            }

            builder.AppendLine("        return copied;");
            builder.AppendLine("    }");
        }

        /// <summary>
        /// Renders the conversion from an Agent-supplied value to a declared type, or null when there is none.
        /// </summary>
        /// <remarks>
        /// Every branch names its destination in the call, so the destination is always a compile-time fact and
        /// no conversion is ever driven by a runtime <see cref="System.Type"/>. A type with no branch is left
        /// unassignable on purpose: writing a default into a POCO the Agent described but did not build would be
        /// worse than refusing it.
        /// </remarks>
        private static string RenderConversion(ITypeSymbol type, string value)
        {
            if (type is INamedTypeSymbol named
                && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T
                && named.TypeArguments.Length == 1)
            {
                var inner = RenderConversion(named.TypeArguments[0], value);
                return $"({value} is null ? null : {inner})";
            }

            if (type.TypeKind == TypeKind.Enum)
                return $"global::VeloxDev.AI.AIContextConvert.ToEnum<{FullTypeOf(type)}>({value})";

            var fromSpecialType = type.SpecialType switch
            {
                SpecialType.System_String => $"global::VeloxDev.AI.AIContextConvert.ToText({value})",
                SpecialType.System_Int32 => $"global::VeloxDev.AI.AIContextConvert.ToInt32({value})",
                SpecialType.System_Int64 => $"global::VeloxDev.AI.AIContextConvert.ToInt64({value})",
                SpecialType.System_Double => $"global::VeloxDev.AI.AIContextConvert.ToDouble({value})",
                SpecialType.System_Decimal => $"global::VeloxDev.AI.AIContextConvert.ToDecimal({value})",
                SpecialType.System_Single => $"(float)global::VeloxDev.AI.AIContextConvert.ToDouble({value})",
                SpecialType.System_Boolean => $"global::VeloxDev.AI.AIContextConvert.ToBoolean({value})",
                SpecialType.System_Byte => $"global::VeloxDev.AI.AIContextConvert.ToByte({value})",
                SpecialType.System_Int16 => $"global::VeloxDev.AI.AIContextConvert.ToInt16({value})",
                SpecialType.System_Char => $"global::VeloxDev.AI.AIContextConvert.ToChar({value})",
                _ => null,
            };

            if (fromSpecialType is not null) return fromSpecialType;

            // 少数几个由 BCL 类型识别的常见形状。没有回退之后这张表就是全部写入能力，所以宁可写全。
            var full = FullTypeOf(type);
            return full switch
            {
                "global::System.DateTime" => $"global::VeloxDev.AI.AIContextConvert.ToDateTime({value})",
                "global::System.TimeSpan" => $"global::VeloxDev.AI.AIContextConvert.ToTimeSpan({value})",
                "global::System.Guid" => $"global::VeloxDev.AI.AIContextConvert.ToGuid({value})",
                // 其余类型直接转型：拿到的东西对就过，不对就抛 —— 由调用方变成一条拒绝说明。
                // 比悄悄写一个默认值好：那个默认值调用方从没提过。
                _ => $"({full}){value}!",
            };
        }

        private static string FullTypeOf(ITypeSymbol type)
            => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // ── 注册 ──

        private static void WriteRegistration(StringBuilder builder, AIContextAssembly assembly, string safeAssembly)
        {
            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Registers <c>{assembly.AssemblyName}</c>'s fragment and accessors when the module loads.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine($"internal static class {safeAssembly}_AIContextRegistration");
            builder.AppendLine("{");
            builder.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
            builder.AppendLine("    internal static void Register()");
            builder.AppendLine("    {");
            builder.AppendLine($"        global::{AIContextNamespace}.AIContextTreeRegistry.RegisterFragment(new {safeAssembly}_AIContextFragment());");

            for (var i = 0; i < assembly.Types.Count; i++)
            {
                builder.AppendLine($"        global::{AIContextNamespace}.AIContextTreeRegistry.RegisterAccessor(new {safeAssembly}_Accessor{i}());");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        // ── 助手 ──

        private static string LastSegment(string path)
        {
            var separator = path.LastIndexOf('/');
            return separator < 0 ? path : path.Substring(separator + 1);
        }

        private static string Sanitize(string name)
        {
            var builder = new StringBuilder(name.Length);
            foreach (var c in name)
            {
                builder.Append(char.IsLetterOrDigit(c) ? c : '_');
            }

            return builder.ToString();
        }

        private static string Escape(string text)
            => text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n");
    }
}
