using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using System.Text;

namespace VeloxDev.Generators.Writers
{
    public class AopWriter : WriterBase
    {
        private bool IsAop { get; set; } = false;

        public override void Initialize(ClassDeclarationSyntax classDeclaration, INamedTypeSymbol namedTypeSymbol)
        {
            base.Initialize(classDeclaration, namedTypeSymbol);
            ReadAopConfig(classDeclaration);
        }

        private void ReadAopConfig(ClassDeclarationSyntax classDeclaration)
        {
            IsAop = classDeclaration.Members
                .OfType<MemberDeclarationSyntax>()
                .Any(member => member.AttributeLists
                    .SelectMany(al => al.Attributes)
                    .Any(attr => attr.Name.ToString() == "AspectOriented"));
        }

        public override bool CanWrite() => IsAop;

        public override string GetFileName()
        {
            if (Syntax == null || Symbol == null) return string.Empty;
            return $"{Syntax.Identifier.Text}_{Symbol.ContainingNamespace.ToDisplayString().Replace('.', '_')}_AOP.g.cs";
        }

        // ── 输出 1: 分部类（保留接口实现契约）──

        public override string[] GenerateBaseInterfaces() =>
        [
            $"{NAMESPACE_VELOX_AOP}.{Syntax?.Identifier.Text}_{Symbol?.ContainingNamespace.ToDisplayString().Replace('.', '_')}_Aop"
        ];
        public override string[] GenerateBaseTypes() => [];

        public override string GenerateBody() => string.Empty;

        // ── 输出 2: 扩展方法类 ──

        public string GetExtensionFileName()
        {
            if (Syntax == null || Symbol == null) return string.Empty;
            return $"{Syntax.Identifier.Text}_{Symbol.ContainingNamespace.ToDisplayString().Replace('.', '_')}_AopExt.g.cs";
        }

        public string WriteExtension()
        {
            if (Syntax == null || Symbol == null || !IsAop)
                return string.Empty;

            var className = Syntax.Identifier.Text;
            var ns = Symbol.ContainingNamespace.ToDisplayString();
            var nsParts = ns.Replace('.', '_');
            var aopInterface = $"global::VeloxDev.AopInterfaces.{className}_{nsParts}_Aop";
            var fullClass = $"global::{ns}.{className}";

            var extClassName = $"{className}_{nsParts}_AopExtensions";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace VeloxDev.AspectOriented;");
            sb.AppendLine();
            sb.AppendLine($"public static class {extClassName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static {aopInterface} Aop(this {fullClass} instance)");
            sb.AppendLine($"        => global::VeloxDev.AspectOriented.AopCache.Resolve<");
            sb.AppendLine($"            {fullClass},");
            sb.AppendLine($"            {aopInterface}>(");
            sb.AppendLine($"            instance,");
            sb.AppendLine($"            static x =>");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                var p = global::VeloxDev.AspectOriented.ProxyEx.CreateProxy<{aopInterface}>(x);");
            sb.AppendLine($"                global::VeloxDev.AspectOriented.Aop.Map(p, x);");
            sb.AppendLine($"                return p;");
            sb.AppendLine($"            }});");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}