using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using System.Text;
using VeloxDev.Generators.Base;

namespace VeloxDev.Generators.Writers
{
    public class AopWriter : WriterBase
    {
        private bool IsAop { get; set; } = false;

        /// <inheritdoc />
        public override void Initialize(ClassDeclarationSyntax classDeclaration, INamedTypeSymbol namedTypeSymbol)
        {
            base.Initialize(classDeclaration, namedTypeSymbol);
            ReadAopConfig(namedTypeSymbol);
        }

        // 基于符号：[AspectOriented] 成员可能不在本写入者拿到的那个 partial 声明上，只从一份声明检测会为整个类型静默地什么都不生成。
        private void ReadAopConfig(INamedTypeSymbol symbol)
        {
            IsAop = AnalizeHelper.IsAopClass(symbol);
        }

        /// <inheritdoc />
        public override bool CanWrite() => IsAop;

        /// <inheritdoc />
        public override string GetFileName()
        {
            if (Syntax == null || Symbol == null) return string.Empty;
            return $"{Syntax.Identifier.Text}_{NamespaceFileSegment()}_AOP.g.cs";
        }

        // 不再往用户类上注入那个接口。曾经需要它，只是为了让 CreateProxy<接口>(x) 编译得过；
        // 改用编译期实现类之后 new {Proxy}(x) 不需要任何转换，而生成的接口现在多了一个**带成员的**
        // 基接口 IAopHookTarget —— 继续让用户类实现它，用户类就必须自己实现 SetHooks，那是荒谬的。
        /// <inheritdoc />
        public override string[] GenerateBaseTypes() => [];

        /// <inheritdoc />
        public override string[] GenerateBaseInterfaces() => [];

        /// <inheritdoc />
        public override string GenerateBody() => string.Empty;

        // ── 输出 2：扩展方法类 ──

        /// <summary>Returns the generated file name for the extension-method class.</summary>
        public string GetExtensionFileName()
        {
            if (Syntax == null || Symbol == null) return string.Empty;
            return $"{Syntax.Identifier.Text}_{NamespaceFileSegment()}_AopExt.g.cs";
        }

        /// <summary>Returns the generated extension-method class source.</summary>
        public string WriteExtension()
        {
            if (Syntax == null || Symbol == null || !IsAop)
                return string.Empty;

            var className = Syntax.Identifier.Text;
            var nsParts = AopNames.Segment(Symbol);
            // 名字统一走 AopNames：接口、代理实现、这个扩展类三者必须对同一个类给出一致的名字。
            var aopInterface = $"global::{AopNames.InterfaceNamespace}.{AopNames.InterfaceFor(Symbol)}";
            var aopProxy = $"global::{AopNames.InterfaceNamespace}.{AopNames.ProxyFor(Symbol)}";
            // 用符号的完全限定名，而不是拼命名空间 —— 全局命名空间下前者是 "<global namespace>.<类>"，非法。
            var fullClass = $"global::{Symbol.ToDisplayString()}";

            var extClassName = $"{className}_{nsParts}_AopExtensions";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("#pragma warning disable");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace VeloxDev.AspectOriented;");
            sb.AppendLine();
            sb.AppendLine($"public static class {extClassName}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static {aopInterface} Aop(this {fullClass} instance)");
            sb.AppendLine($"        => global::VeloxDev.AspectOriented.AopCache.Resolve<");
            sb.AppendLine($"            {fullClass},");
            sb.AppendLine($"            {aopInterface}>(");
            sb.AppendLine($"            instance,");
            sb.AppendLine($"            static x =>");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                var p = new {aopProxy}(x);");
            sb.AppendLine($"                global::VeloxDev.AspectOriented.Aop.Map(p, x);");
            sb.AppendLine($"                return p;");
            sb.AppendLine($"            }});");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}