using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using VeloxDev.Generators.Base;

namespace VeloxDev.Generators.Writers
{
    /// <summary>
    /// Renders one assembly's serializer: a writer per type, and the registration that puts them in the registry.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The emitted code is a straight-line sequence of calls into <c>VeloxDev.Serialization</c>. Every member name
    /// and every type is a literal, so nothing the runtime does needs metadata — which is the point: the format
    /// survives trimming because the only thing that knows the shape of a document is compiled code.
    /// </para>
    /// <para>
    /// One file per assembly, like the context tree: the entries have to agree with one another (a member's type
    /// is another entry's class name), so they are rendered together rather than one type at a time.
    /// </para>
    /// </remarks>
    internal static class VeloxJsonCodeWriter
    {
        private const string SerializationNamespace = "VeloxDev.Serialization";

        internal static string Write(VeloxJsonAssembly assembly, string safeAssembly)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("#pragma warning disable");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine($"namespace {SerializationNamespace}.Generated;");
            builder.AppendLine();

            for (var i = 0; i < assembly.Types.Count; i++)
            {
                var type = assembly.Types[i];
                type.WriterClassName = $"{safeAssembly}_JsonWriter{i}";
                type.ReaderClassName = $"{safeAssembly}_JsonReader{i}";

                WriteTypeWriter(builder, type);
                builder.AppendLine();
                WriteTypeReader(builder, type);
                builder.AppendLine();
            }

            WriteRegistration(builder, assembly, safeAssembly);

            return builder.ToString();
        }

        private static void WriteTypeWriter(StringBuilder builder, VeloxJsonType type)
        {
            var target = FullTypeOf(type.Symbol);

            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Writes <c>{Escape(type.FullName)}</c>.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine($"internal sealed class {type.WriterClassName} : global::{SerializationNamespace}.IVeloxJsonWriter");
            builder.AppendLine("{");
            builder.AppendLine("    public void Write(");
            builder.AppendLine($"        global::{SerializationNamespace}.VeloxJsonWriter writer,");
            builder.AppendLine("        object value,");
            builder.AppendLine("        global::System.Type? declaredType)");
            builder.AppendLine("    {");
            builder.AppendLine($"        var t = ({target})value;");
            builder.AppendLine("        if (!writer.WriteStartObject(t, declaredType)) return;");
            builder.AppendLine();

            // 钩子只在真的写这一个实例时跑 —— 写成 $ref 的那次没有内容要准备。
            if (Implements(type, "IVeloxJsonSerializing"))
                builder.AppendLine($"        ((global::{SerializationNamespace}.IVeloxJsonSerializing)t).OnSerializing();");

            builder.AppendLine();

            foreach (var member in type.Members)
            {
                WriteMember(builder, member);
            }

            builder.AppendLine();

            if (Implements(type, "IVeloxJsonSerialized"))
            {
                builder.AppendLine($"        ((global::{SerializationNamespace}.IVeloxJsonSerialized)t).OnSerialized();");
            }

            builder.AppendLine("        writer.WriteEndObject();");
            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        /// <summary>
        /// Writes one member: its name, then its value.
        /// </summary>
        /// <remarks>
        /// Every member goes through the same entry point. Which of the four shapes a value is — a scalar, a
        /// container, a registered object — is decided there from the declared type and the value, so the
        /// generated code stays one line per member and the format's rules live in exactly one place.
        /// </remarks>
        private static void WriteMember(StringBuilder builder, VeloxJsonMember member)
        {
            var declaredType = FullTypeOf(member.DeclaredType);

            // 被排除的成员连名字都不写：快照模式靠这条把节点引用挡在文件外。
            builder.AppendLine($"        if (!global::{SerializationNamespace}.VeloxJsonSerializer.IsExcluded(typeof({declaredType})))");
            builder.AppendLine("        {");
            builder.AppendLine($"            writer.WriteMemberName(\"{Escape(member.Name)}\");");
            builder.AppendLine($"            global::{SerializationNamespace}.VeloxJsonSerializer.WriteValue(");
            builder.AppendLine($"                writer, t.{member.Name}, typeof({declaredType}));");
            builder.AppendLine("        }");
        }

        /// <summary>
        /// Emits the reader for one type: a factory and a member dispatch.
        /// </summary>
        /// <remarks>
        /// Scalars are read by the generated code because the declared type is known at compile time — an enum
        /// is a cast from its number, never a lookup. Objects and containers go through the runtime, which is
        /// where the reference table and the type-name dispatch live.
        /// </remarks>
        private static void WriteTypeReader(StringBuilder builder, VeloxJsonType type)
        {
            var target = FullTypeOf(type.Symbol);

            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Reads <c>{Escape(type.FullName)}</c>.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine($"internal sealed class {type.ReaderClassName} : global::{SerializationNamespace}.IVeloxJsonReader");
            builder.AppendLine("{");

            // 没有公开无参构造的类型建不出来 —— 面板视图模型是这种。写入照发，读取明说建不出来，
            // 而不是生成一个编译不过的 `new`。
            if (HasPublicParameterlessConstructor(type.Symbol))
            {
                builder.AppendLine($"    public object Create() => new {target}();");
            }
            else
            {
                builder.AppendLine("    public object Create() => throw new global::System.NotSupportedException(");
                builder.AppendLine($"        \"{Escape(type.FullName)} has no public parameterless constructor, so a document cannot be read into it.\");");
            }

            builder.AppendLine();
            builder.AppendLine($"    public void Read(global::{SerializationNamespace}.VeloxJsonReader reader, object target)");
            builder.AppendLine("    {");
            builder.AppendLine($"        var t = ({target})target;");
            builder.AppendLine();

            if (Implements(type, "IVeloxJsonDeserializing"))
                builder.AppendLine($"        ((global::{SerializationNamespace}.IVeloxJsonDeserializing)t).OnDeserializing();");

            builder.AppendLine();
            builder.AppendLine("        while (reader.NextMember(out var name))");
            builder.AppendLine("        {");
            builder.AppendLine("            switch (name)");
            builder.AppendLine("            {");

            foreach (var member in type.Members)
            {
                // 每个 case 各起一个作用域：多个分支都用到模式变量的话，同一个 switch 里会撞名。
                builder.AppendLine($"                case \"{Escape(member.Name)}\":");
                builder.AppendLine("                {");
                builder.AppendLine($"                    {ReadMember(member)}");
                builder.AppendLine("                    break;");
                builder.AppendLine("                }");
            }

            // 读不懂的成员跳过，而不是失败：旧版本读新文档时该继续走。
            builder.AppendLine("                default: reader.SkipValue(); break;");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            builder.AppendLine("        reader.FinishObject();");
            builder.AppendLine();

            if (Implements(type, "IVeloxJsonDeserialized"))
            {
                builder.AppendLine("        // 全部成员都读完才回调 —— 依赖旁边那个成员的成员等的是这个时刻。");
                builder.AppendLine($"        ((global::{SerializationNamespace}.IVeloxJsonDeserialized)t).OnDeserialized();");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        /// <summary>Reads one member's value back into the target.</summary>
        private static string ReadMember(VeloxJsonMember member)
        {
            var access = "t." + member.Name;

            switch (member.Kind)
            {
                case VeloxJsonMemberKind.Collection:
                    // 只有可变列表能追加；只读集合这一版读不回来，跳过而不是假装成功。
                    if (!ImplementsInterface(member.DeclaredType, "System.Collections.IList"))
                        return "reader.SkipValue();";

                    // 追加而不是替换：构造函数可能已经填过，契约一贯是往里加。
                    return $"if ({access} is {{ }} list) global::{SerializationNamespace}.VeloxJsonSerializer.ReadArray(" +
                           $"reader, list, typeof({FullTypeOf(member.ElementType!)})); else reader.SkipValue();";

                case VeloxJsonMemberKind.Dictionary:
                    return $"if ({access} is {{ }} map) global::{SerializationNamespace}.VeloxJsonSerializer.ReadMap(" +
                           $"reader, map, typeof({FullTypeOf(FirstTypeArgument(member.DeclaredType))}), " +
                           $"typeof({FullTypeOf(member.ElementType!)}), interfaceKeys: {(member.InterfaceKeyed ? "true" : "false")}); " +
                           "else reader.SkipValue();";

                case VeloxJsonMemberKind.Scalar:
                    return $"{access} = {ScalarRead(member.DeclaredType)};";

                default:
                    return $"{access} = ({FullTypeOf(member.DeclaredType)})global::{SerializationNamespace}.VeloxJsonSerializer" +
                           $".ReadValue(reader, typeof({FullTypeOf(member.DeclaredType)}), {access})!;";
            }
        }

        /// <summary>The read that produces one scalar, chosen from its declared type.</summary>
        private static string ScalarRead(ITypeSymbol type)
        {
            // 可空值类型：缺值时文档里就是 null，读法与底层类型一样，只是结果可能为空。
            var underlying = VeloxJsonModelBuilder.UnwrapNullable(type);
            if (!SymbolEqualityComparer.Default.Equals(underlying, type))
                return $"(reader.NextIsNull() ? null : {ScalarRead(underlying)})";

            if (type.TypeKind == TypeKind.Enum)
                return $"({FullTypeOf(type)})reader.ReadInt64()";

            return type.SpecialType switch
            {
                SpecialType.System_String => "reader.ReadString()",
                SpecialType.System_Int32 => "reader.ReadInt32()",
                SpecialType.System_Int64 => "reader.ReadInt64()",
                SpecialType.System_Double => "reader.ReadDouble()",
                SpecialType.System_Single => "reader.ReadSingle()",
                SpecialType.System_Decimal => "reader.ReadDecimal()",
                SpecialType.System_Boolean => "reader.ReadBoolean()",
                SpecialType.System_Char => "reader.ReadText()[0]",
                SpecialType.System_Byte => "(byte)reader.ReadInt32()",
                SpecialType.System_Int16 => "(short)reader.ReadInt32()",
                SpecialType.System_Object => $"global::{SerializationNamespace}.VeloxJsonSerializer.ReadUnknown(reader)",
                _ => type.ToDisplayString() switch
                {
                    "System.Guid" => "reader.ReadGuid()",
                    "System.DateTime" => "global::System.DateTime.Parse(reader.ReadText(), global::System.Globalization.CultureInfo.InvariantCulture)",
                    "System.TimeSpan" => "global::System.TimeSpan.Parse(reader.ReadText(), global::System.Globalization.CultureInfo.InvariantCulture)",
                    _ => $"({FullTypeOf(type)})global::{SerializationNamespace}.VeloxJsonSerializer.ReadValue(reader, typeof({FullTypeOf(type)}), null)!",
                },
            };
        }

        /// <summary>Whether the type can be constructed with no arguments.</summary>
        private static bool HasPublicParameterlessConstructor(INamedTypeSymbol symbol)
            => symbol.TypeKind == TypeKind.Struct
               || symbol.InstanceConstructors.Any(static c =>
                      c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);

        /// <summary>Whether a declared type implements a framework interface.</summary>
        private static bool ImplementsInterface(ITypeSymbol type, string metadataName)
            => type.AllInterfaces.Any(i =>
                i.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                 .Replace("global::", string.Empty) == metadataName);

        /// <summary>The first type argument of a declared type, for a map's key type.</summary>
        private static ITypeSymbol FirstTypeArgument(ITypeSymbol type)
            => type is INamedTypeSymbol named && named.TypeArguments.Length > 0
                ? named.TypeArguments[0]
                : type;

        private static void WriteRegistration(
            StringBuilder builder,
            VeloxJsonAssembly assembly,
            string safeAssembly)
        {
            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Registers <c>{Escape(assembly.AssemblyName)}</c>'s serializers when the module loads.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine($"internal static class {safeAssembly}_JsonRegistration");
            builder.AppendLine("{");
            builder.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
            builder.AppendLine("    internal static void Register()");
            builder.AppendLine("    {");

            for (var i = 0; i < assembly.Types.Count; i++)
            {
                var type = assembly.Types[i];
                var target = FullTypeOf(type.Symbol);

                builder.AppendLine($"        global::{SerializationNamespace}.VeloxJsonRegistry.RegisterWriter(typeof({target}), new {type.WriterClassName}());");
                builder.AppendLine($"        global::{SerializationNamespace}.VeloxJsonRegistry.RegisterReader(typeof({target}), new {type.ReaderClassName}());");
                builder.AppendLine($"        global::{SerializationNamespace}.VeloxJsonRegistry.RegisterName(typeof({target}), \"{Escape(type.WrittenName)}\");");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        /// <summary>
        /// Whether a type implements one of the serialization callback interfaces.
        /// </summary>
        /// <remarks>
        /// Decided at compile time rather than by a <c>is</c> test: these types are sealed, so the compiler
        /// already knows the answer and would reject a pattern that can never match.
        /// </remarks>
        private static bool Implements(VeloxJsonType type, string interfaceName)
            => type.Symbol.AllInterfaces.Any(i =>
                i.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                 .Replace("global::", string.Empty) == $"{SerializationNamespace}.{interfaceName}");

        private static string FullTypeOf(ITypeSymbol type)
            => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        private static string Escape(string text)
            => text.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
