using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using VeloxDev.Generators.Base;

namespace VeloxDev.Generators.Writers
{
    /// <summary>
    /// Renders one assembly's serializer: a writer per type, and the registration that puts them in the registry.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The emitted code is a straight-line sequence of calls into <c>VeloxDev.Serialization</c>. Every member name
    /// and every type is a literal, so nothing the runtime does needs metadata — which is the point: the format
    /// survives trimming because the only thing that knows the shape of a document is compiled code.
    /// </para>
    /// <para>
    /// One file per assembly, like the context tree: the entries have to agree with one another (a member's type
    /// is another entry's class name), so they are rendered together rather than one type at a time.
    /// </para>
    /// </remarks>
    internal static class VeloxJsonCodeWriter
    {
        private const string SerializationNamespace = "VeloxDev.Serialization";

        internal static string Write(VeloxJsonAssembly assembly, string safeAssembly)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("#pragma warning disable");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine($"namespace {SerializationNamespace}.Generated;");
            builder.AppendLine();

            for (var i = 0; i < assembly.Types.Count; i++)
            {
                var type = assembly.Types[i];
                type.WriterClassName = $"{safeAssembly}_JsonWriter{i}";
                type.ReaderClassName = $"{safeAssembly}_JsonReader{i}";

                WriteTypeWriter(builder, type);
                builder.AppendLine();
                WriteTypeReader(builder, type);
                builder.AppendLine();
            }

            WriteRegistration(builder, assembly, safeAssembly);

            return builder.ToString();
        }

        private static void WriteTypeWriter(StringBuilder builder, VeloxJsonType type)
        {
            var target = FullTypeOf(type.Symbol);

            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Writes <c>{Escape(type.FullName)}</c>.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine($"internal sealed class {type.WriterClassName} : global::{SerializationNamespace}.IVeloxJsonWriter");
            builder.AppendLine("{");
            WriteWriterBody(builder, type, target, async: false);
            builder.AppendLine();
            WriteWriterBody(builder, type, target, async: true);
            builder.AppendLine("}");
        }

        /// <summary>
        /// Emits one of the two write methods: the synchronous one, or the asynchronous one.
        /// </summary>
        /// <remarks>
        /// They are the same sequence of member writes; only the calls differ, and only because a stream output
        /// has to await its handovers. Emitting both keeps the in-memory path free of state machines it would
        /// never need — the asynchronous one is reached only through a stream or reader entry point.
        /// </remarks>
        private static void WriteWriterBody(StringBuilder builder, VeloxJsonType type, string target, bool async)
        {
            var wait = async ? "await " : string.Empty;
            var configure = async ? ".ConfigureAwait(false)" : string.Empty;
            var returns = async ? "async global::System.Threading.Tasks.Task" : "void";

            builder.AppendLine($"    public {returns} {(async ? "WriteAsync" : "Write")}(");
            builder.AppendLine($"        global::{SerializationNamespace}.VeloxJsonWriter writer,");
            builder.AppendLine("        object value,");
            builder.AppendLine("        global::System.Type? declaredType)");
            builder.AppendLine("    {");
            builder.AppendLine($"        var t = ({target})value;");
            builder.AppendLine($"        if (!{wait}writer.{(async ? "WriteStartObjectAsync" : "WriteStartObject")}(t, declaredType){configure}) return;");
            builder.AppendLine();

            // 钩子只在真的写这一个实例时跑 —— 写成 $ref 的那次没有内容要准备。
            WriteHooks(builder, type.Serializing, "        ");

            builder.AppendLine();

            foreach (var member in type.Members)
            {
                WriteMember(builder, member, async);
            }

            builder.AppendLine();

            WriteHooks(builder, type.Serialized, "        ");

            builder.AppendLine($"        {wait}writer.{(async ? "WriteEndObjectAsync" : "WriteEndObject")}(){configure};");
            builder.AppendLine("    }");
        }

        /// <summary>
        /// Writes one member: its name, then its value.
        /// </summary>
        /// <remarks>
        /// Every member goes through the same entry point. Which of the four shapes a value is — a scalar, a
        /// container, a registered object — is decided there from the declared type and the value, so the
        /// generated code stays one line per member and the format's rules live in exactly one place.
        /// </remarks>
        private static void WriteMember(StringBuilder builder, VeloxJsonMember member, bool async)
        {
            var declaredType = FullTypeOf(member.DeclaredType);
            var wait = async ? "await " : string.Empty;
            var configure = async ? ".ConfigureAwait(false)" : string.Empty;

            // 被排除的成员连名字都不写：快照模式靠这条把节点引用挡在文件外。
            var excluded = $"!global::{SerializationNamespace}.VeloxJsonSerializer.IsExcluded(typeof({declaredType}))";
            var guard = WriteGuard(member, declaredType);

            // 条件写出不需要读侧配合：缺一个成员，与读到一个没见过的成员，走的是同一条路。
            builder.AppendLine($"        if ({(guard.Length == 0 ? excluded : $"{guard} {excluded}")})");
            builder.AppendLine("        {");
            builder.AppendLine($"            {wait}writer.{(async ? "WriteMemberNameAsync" : "WriteMemberName")}(\"{Escape(member.DocumentName)}\"){configure};");
            builder.AppendLine($"            {wait}global::{SerializationNamespace}.VeloxJsonSerializer.{(async ? "WriteValueAsync" : "WriteValue")}(");
            builder.AppendLine($"                writer, t.{member.Name}, typeof({declaredType})){configure};");
            builder.AppendLine("        }");
        }

        /// <summary>
        /// The condition that has to hold for a member to be written, or an empty string when it is
        /// unconditional.
        /// </summary>
        /// <remarks>
        /// <c>WhenWritingDefault</c> is a null test for a reference type rather than an equality one: the default
        /// of a reference type is null, and comparing through <c>EqualityComparer</c> would drag a type's own
        /// <c>Equals</c> into a decision the standard attribute does not make.
        /// </remarks>
        private static string WriteGuard(VeloxJsonMember member, string declaredType)
            => member.WriteCondition switch
            {
                VeloxJsonWriteCondition.WhenNotNull => $"t.{member.Name} is not null &&",
                VeloxJsonWriteCondition.WhenNotDefault when !member.DeclaredType.IsValueType => $"t.{member.Name} is not null &&",
                VeloxJsonWriteCondition.WhenNotDefault =>
                    $"!global::System.Collections.Generic.EqualityComparer<{declaredType}>.Default.Equals(t.{member.Name}, default!) &&",
                _ => string.Empty,
            };

        /// <summary>
        /// Emits the reader for one type: a factory and a member dispatch.
        /// </summary>
        /// <remarks>
        /// Scalars are read by the generated code because the declared type is known at compile time — an enum
        /// is a cast from its number, never a lookup. Objects and containers go through the runtime, which is
        /// where the reference table and the type-name dispatch live.
        /// </remarks>
        private static void WriteTypeReader(StringBuilder builder, VeloxJsonType type)
        {
            var target = FullTypeOf(type.Symbol);

            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Reads <c>{Escape(type.FullName)}</c>.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine($"internal sealed class {type.ReaderClassName} : global::{SerializationNamespace}.IVeloxJsonReader");
            builder.AppendLine("{");

            // 没有公开无参构造的类型建不出来 —— 面板视图模型是这种。写入照发，读取明说建不出来，
            // 而不是生成一个编译不过的 `new`。
            if (HasPublicParameterlessConstructor(type.Symbol))
            {
                builder.AppendLine($"    public object Create() => new {target}();");
            }
            else
            {
                builder.AppendLine("    public object Create() => throw new global::System.NotSupportedException(");
                builder.AppendLine($"        \"{Escape(type.FullName)} has no public parameterless constructor, so a document cannot be read into it.\");");
            }

            builder.AppendLine();
            WriteReaderBody(builder, type, target, async: false);
            builder.AppendLine();
            WriteReaderBody(builder, type, target, async: true);
            builder.AppendLine("}");
        }

        /// <summary>
        /// Emits one of the two read methods: the synchronous one, or the asynchronous one.
        /// </summary>
        /// <remarks>
        /// Same dispatch, same order; the asynchronous one awaits its refills. <c>MemberNameEquals</c> stays
        /// synchronous on both — comparing a name in the buffer does no I/O.
        /// </remarks>
        private static void WriteReaderBody(StringBuilder builder, VeloxJsonType type, string target, bool async)
        {
            var wait = async ? "await " : string.Empty;
            var configure = async ? ".ConfigureAwait(false)" : string.Empty;
            var returns = async ? "async global::System.Threading.Tasks.Task" : "void";

            builder.AppendLine($"    public {returns} {(async ? "ReadAsync" : "Read")}(global::{SerializationNamespace}.VeloxJsonReader reader, object target)");
            builder.AppendLine("    {");
            builder.AppendLine($"        var t = ({target})target;");
            builder.AppendLine();

            WriteHooks(builder, type.Deserializing, "        ");

            builder.AppendLine();
            // 成员名不落成字符串：NextMember() 只定位，MemberNameEquals 就地拿原文与字面量比。
            // 换掉原来的 `while (NextMember(out var name)) switch (name)` —— 那条每读一个成员都要
            // 先分配一个字符串，只为和字面量比一次就丢掉。
            builder.AppendLine($"        while ({wait}reader.{(async ? "NextMemberAsync" : "NextMember")}(){configure})");
            builder.AppendLine("        {");

            var first = true;
            foreach (var member in type.Members)
            {
                // 只写得出去的成员（计算属性）没有读法：不给它发分支，文档里那个值就落到下面那条
                // 「读不懂的成员跳过」上 —— 与「旧版本读到新成员」走的是同一条路。
                if (member.WriteOnly) continue;

                // 每个分支各起一个作用域：多个分支都用到模式变量的话会撞名。
                builder.AppendLine($"            {(first ? "if" : "else if")} (reader.MemberNameEquals(\"{Escape(member.DocumentName)}\"))");
                builder.AppendLine("            {");
                builder.AppendLine($"                {ReadMember(member, async)}");
                builder.AppendLine("            }");

                first = false;
            }

            // 读不懂的成员跳过，而不是失败：旧版本读新文档时该继续走。
            var skip = $"{wait}reader.{(async ? "SkipValueAsync" : "SkipValue")}(){configure};";
            builder.AppendLine(first ? $"            {skip}" : $"            else {skip}");
            builder.AppendLine("        }");
            builder.AppendLine($"        {wait}reader.{(async ? "FinishObjectAsync" : "FinishObject")}(){configure};");
            builder.AppendLine();

            if (type.Deserialized.Count > 0)
            {
                builder.AppendLine("        // 全部成员都读完才回调 —— 依赖旁边那个成员的成员等的是这个时刻。");
                WriteHooks(builder, type.Deserialized, "        ");
            }

            builder.AppendLine("    }");
        }

        /// <summary>Reads one member's value back into the target.</summary>
        private static string ReadMember(VeloxJsonMember member, bool async)
        {
            var access = "t." + member.Name;
            var wait = async ? "await " : string.Empty;
            var configure = async ? ".ConfigureAwait(false)" : string.Empty;
            var skip = $"{wait}reader.{(async ? "SkipValueAsync" : "SkipValue")}(){configure};";

            switch (member.Kind)
            {
                case VeloxJsonMemberKind.Collection:
                    // 只有可变列表能追加；只读集合这一版读不回来，跳过而不是假装成功。
                    if (!ImplementsInterface(member.DeclaredType, "System.Collections.IList"))
                        return skip;

                    // 追加而不是替换：构造函数可能已经填过，契约一贯是往里加。
                    return $"if ({access} is {{ }} list) {wait}global::{SerializationNamespace}.VeloxJsonSerializer" +
                           $".{(async ? "ReadArrayAsync" : "ReadArray")}(" +
                           $"reader, list, typeof({FullTypeOf(member.ElementType!)})){configure}; else {skip}";

                case VeloxJsonMemberKind.Dictionary:
                    return $"if ({access} is {{ }} map) {wait}global::{SerializationNamespace}.VeloxJsonSerializer" +
                           $".{(async ? "ReadMapAsync" : "ReadMap")}(" +
                           $"reader, map, typeof({FullTypeOf(FirstTypeArgument(member.DeclaredType))}), " +
                           $"typeof({FullTypeOf(member.ElementType!)}), interfaceKeys: {(member.InterfaceKeyed ? "true" : "false")}){configure}; " +
                           $"else {skip}";

                case VeloxJsonMemberKind.Scalar:
                    return $"{access} = {ScalarRead(member.DeclaredType, async)};";

                default:
                    return $"{access} = ({FullTypeOf(member.DeclaredType)}){wait}global::{SerializationNamespace}.VeloxJsonSerializer" +
                           $".{(async ? "ReadValueAsync" : "ReadValue")}(reader, typeof({FullTypeOf(member.DeclaredType)}), {access}){configure}!;";
            }
        }

        /// <summary>The read that produces one scalar, chosen from its declared type.</summary>
        private static string ScalarRead(ITypeSymbol type, bool async)
        {
            var wait = async ? "await " : string.Empty;
            var configure = async ? ".ConfigureAwait(false)" : string.Empty;

            string Call(string name) => $"{wait}reader.{name}{(async ? "Async" : string.Empty)}(){configure}";

            // 可空值类型：缺值时文档里就是 null，读法与底层类型一样，只是结果可能为空。
            var underlying = VeloxJsonModelBuilder.UnwrapNullable(type);
            if (!SymbolEqualityComparer.Default.Equals(underlying, type))
                return $"({Call("NextIsNull")} ? null : {ScalarRead(underlying, async)})";

            if (type.TypeKind == TypeKind.Enum)
                return $"({FullTypeOf(type)}){Call("ReadInt64")}";

            return type.SpecialType switch
            {
                SpecialType.System_String => Call("ReadString"),
                SpecialType.System_Int32 => Call("ReadInt32"),
                SpecialType.System_Int64 => Call("ReadInt64"),
                SpecialType.System_Double => Call("ReadDouble"),
                SpecialType.System_Single => Call("ReadSingle"),
                SpecialType.System_Decimal => Call("ReadDecimal"),
                SpecialType.System_Boolean => Call("ReadBoolean"),
                SpecialType.System_Char => $"({Call("ReadText")})[0]",
                SpecialType.System_Byte => $"(byte)({Call("ReadInt32")})",
                SpecialType.System_Int16 => $"(short)({Call("ReadInt32")})",
                SpecialType.System_Object =>
                    $"{wait}global::{SerializationNamespace}.VeloxJsonSerializer.{(async ? "ReadUnknownAsync" : "ReadUnknown")}(reader){configure}",
                _ => type.ToDisplayString() switch
                {
                    "System.Guid" => Call("ReadGuid"),
                    "System.DateTime" => $"global::System.DateTime.Parse({Call("ReadText")}, global::System.Globalization.CultureInfo.InvariantCulture)",
                    "System.TimeSpan" => $"global::System.TimeSpan.Parse({Call("ReadText")}, global::System.Globalization.CultureInfo.InvariantCulture)",
                    _ => $"({FullTypeOf(type)}){wait}global::{SerializationNamespace}.VeloxJsonSerializer" +
                         $".{(async ? "ReadValueAsync" : "ReadValue")}(reader, typeof({FullTypeOf(type)}), null){configure}!",
                },
            };
        }

        /// <summary>Whether the type can be constructed with no arguments.</summary>
        private static bool HasPublicParameterlessConstructor(INamedTypeSymbol symbol)
            => symbol.TypeKind == TypeKind.Struct
               || symbol.InstanceConstructors.Any(static c =>
                      c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public);

        /// <summary>Whether a declared type implements a framework interface.</summary>
        private static bool ImplementsInterface(ITypeSymbol type, string metadataName)
            => type.AllInterfaces.Any(i =>
                i.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                 .Replace("global::", string.Empty) == metadataName);

        /// <summary>The first type argument of a declared type, for a map's key type.</summary>
        private static ITypeSymbol FirstTypeArgument(ITypeSymbol type)
            => type is INamedTypeSymbol named && named.TypeArguments.Length > 0
                ? named.TypeArguments[0]
                : type;

        private static void WriteRegistration(
            StringBuilder builder,
            VeloxJsonAssembly assembly,
            string safeAssembly)
        {
            builder.AppendLine("/// <summary>");
            builder.AppendLine($"/// Registers <c>{Escape(assembly.AssemblyName)}</c>'s serializers when the module loads.");
            builder.AppendLine("/// </summary>");
            builder.AppendLine($"internal static class {safeAssembly}_JsonRegistration");
            builder.AppendLine("{");
            builder.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
            builder.AppendLine("    internal static void Register()");
            builder.AppendLine("    {");

            for (var i = 0; i < assembly.Types.Count; i++)
            {
                var type = assembly.Types[i];
                var target = FullTypeOf(type.Symbol);

                builder.AppendLine($"        global::{SerializationNamespace}.VeloxJsonRegistry.RegisterWriter(typeof({target}), new {type.WriterClassName}());");
                builder.AppendLine($"        global::{SerializationNamespace}.VeloxJsonRegistry.RegisterReader(typeof({target}), new {type.ReaderClassName}());");
                builder.AppendLine($"        global::{SerializationNamespace}.VeloxJsonRegistry.RegisterName(typeof({target}), \"{Escape(type.WrittenName)}\");");
            }

            // 嵌套容器没有生成条目 —— 它按形状读，缺的只是「谁来 new」。所以登记的是一句构造，
            // 而不是一个 IVeloxJsonReader：形状规则留在序列化器一处，和写侧同源。
            foreach (var container in assembly.Containers)
            {
                builder.AppendLine($"        global::{SerializationNamespace}.VeloxJsonRegistry.RegisterContainerFactory(typeof({FullTypeOf(container.Symbol)}), {ContainerFactory(container)});");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        // 造一个嵌容器的表达式。声明成接口的（IReadOnlyDictionary<K,V>、IList<T>）new 不出来，
        // 落到分类器已经当作它形状的那个具体实现上。
        private static string ContainerFactory(VeloxJsonContainer container)
        {
            if (container.Symbol.TypeKind == TypeKind.Interface)
            {
                var element = FullTypeOf(container.ElementType);

                return container.Kind == VeloxJsonMemberKind.Dictionary
                    ? $"() => new global::System.Collections.Generic.Dictionary<{FullTypeOf(container.KeyType!)}, {element}>()"
                    : $"() => new global::System.Collections.Generic.List<{element}>()";
            }

            return $"() => new {FullTypeOf(container.Symbol)}()";
        }

        /// <summary>
        /// Emits one call per callback, base type first — the order the BCL formatter calls them in.
        /// </summary>
        /// <remarks>
        /// The <c>StreamingContext</c> the BCL shape takes is passed as <c>default</c>: this format has no context
        /// to hand over, and inventing one would be a lie the callback could act on.
        /// </remarks>
        private static void WriteHooks(StringBuilder builder, IReadOnlyList<VeloxJsonHook> hooks, string indent)
        {
            foreach (var hook in hooks)
            {
                var call = hook.TakesContext
                    ? $"{hook.Name}(default(global::System.Runtime.Serialization.StreamingContext))"
                    : $"{hook.Name}()";

                builder.AppendLine($"{indent}t.{call};");
            }
        }

        private static string FullTypeOf(ITypeSymbol type)
            => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        private static string Escape(string text)
            => text.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
