using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using VeloxDev.Generators.Base;

namespace VeloxDev.Generators.Writers
{
    public abstract class WriterBase : ICodeWriter
    {
        public const string NAMESPACE_VELOX_TIMELINE = "global::VeloxDev.TimeLine";
        public const string NAMESPACE_VELOX_IMVVM = "global::VeloxDev.MVVM";
        public const string NAMESPACE_VELOX_MVVM = "global::VeloxDev.MVVM";
        public const string NAMESPACE_VELOX_AOP = "global::VeloxDev.AopInterfaces";
        public const string NAMESPACE_SYSTEM_MVVM = "global::System.ComponentModel";
        public const string NAMESPACE_VELOX_IWORKFLOW = "global::VeloxDev.WorkflowSystem";
        public const string NAMESPACE_VELOX_WORKFLOW = "global::VeloxDev.WorkflowSystem";

        public ClassDeclarationSyntax? Syntax { get; protected set; }
        public INamedTypeSymbol? Symbol { get; protected set; }
        public List<ClassDeclarationSyntax>? OuterClasses { get; protected set; }

        public virtual void Initialize(ClassDeclarationSyntax classDeclaration, INamedTypeSymbol namedTypeSymbol)
        {
            Syntax = classDeclaration;
            Symbol = namedTypeSymbol;

            // If it's a nested class, collect the outer classes
            OuterClasses = [];
            var parent = classDeclaration.Parent;
            while (parent is ClassDeclarationSyntax outerClass)
            {
                OuterClasses.Insert(0, outerClass);
                parent = parent.Parent;
            }
        }

        public virtual string Write()
        {
            if (Syntax == null || Symbol == null) return string.Empty;

            StringBuilder sourceBuilder = new();

            // Get the type parameters
            string typeParameters = GetTypeParameters();

            // Get the constraint clauses
            string constraints = GetConstraints();

            // Get the base type and interface list
            string baseTypes = GetBaseTypes();

            sourceBuilder.AppendLine("// <auto-generated>");
            sourceBuilder.AppendLine("#pragma warning disable");
            sourceBuilder.AppendLine("#nullable enable");
            sourceBuilder.AppendLine();

            // If it's not a nested class, or the outermost class isn't in a namespace, add the namespace
            if (OuterClasses == null || OuterClasses.Count == 0)
            {
                sourceBuilder.AppendLine($"namespace {Symbol.ContainingNamespace};");
                sourceBuilder.AppendLine();
            }

            // If this is a nested class, generate the outer classes
            if (OuterClasses != null && OuterClasses.Count > 0)
            {
                // Start from the outermost class
                var outermostClass = OuterClasses[0];
                sourceBuilder.AppendLine($"namespace {Symbol.ContainingNamespace};");
                sourceBuilder.AppendLine();

                // Format the modifiers, ensuring the partial keyword is positioned correctly
                var modifiers = FormatModifiers(outermostClass.Modifiers.ToString());
                sourceBuilder.AppendLine($"{modifiers}class {outermostClass.Identifier.Text}");
                sourceBuilder.AppendLine("{");

                // Generate the inner classes
                for (int i = 1; i < OuterClasses.Count; i++)
                {
                    var outerClass = OuterClasses[i];
                    modifiers = FormatModifiers(outerClass.Modifiers.ToString());
                    sourceBuilder.AppendLine($"{modifiers}class {outerClass.Identifier.Text}");
                    sourceBuilder.AppendLine("{");
                }
            }

            // Generate the current class declaration
            var currentModifiers = FormatModifiers(Syntax.Modifiers.ToString());
            sourceBuilder.AppendLine($"{currentModifiers}class {Syntax.Identifier.Text}{typeParameters}{baseTypes}{constraints}");
            sourceBuilder.AppendLine("{");
            sourceBuilder.AppendLine(GenerateBody());
            sourceBuilder.AppendLine("}");

            // Close all outer classes (if it's a nested class)
            if (OuterClasses != null && OuterClasses.Count > 0)
            {
                for (int i = 0; i < OuterClasses.Count; i++)
                {
                    sourceBuilder.AppendLine("}");
                }
            }

            return sourceBuilder.ToString();
        }

        private string GetTypeParameters()
        {
            if (Syntax?.TypeParameterList == null)
                return string.Empty;

            return $"<{string.Join(", ", Syntax.TypeParameterList.Parameters.Select(p => p.ToString()))}>";
        }

        private string GetConstraints()
        {
            if (Syntax?.ConstraintClauses == null || !Syntax.ConstraintClauses.Any())
                return string.Empty;

            var constraints = new StringBuilder();

            foreach (var constraintClause in Syntax.ConstraintClauses)
            {
                // Add the complete constraint clause directly
                // Type names in constraints are resolved in the user code's namespace context
                constraints.Append(" ").Append(constraintClause.ToString());
            }

            return constraints.ToString();
        }

        private string GetBaseTypes()
        {
            if (Symbol == null)
                return string.Empty;

            var baseTypes = new List<string>();

            // 1. Add the original class's base types and interfaces (fully qualified names from the semantic model)
            if (Symbol.Interfaces.Length > 0)
            {
                // Get the fully qualified name of every interface
                foreach (var interfaceSymbol in Symbol.Interfaces)
                {
                    string fullName = GetFullyQualifiedTypeName(interfaceSymbol);
                    if (!string.IsNullOrEmpty(fullName))
                    {
                        baseTypes.Add(fullName);
                    }
                }
            }

            // 2. Add the base class (if any)
            if (Symbol.BaseType != null && Symbol.BaseType.SpecialType != SpecialType.System_Object)
            {
                string baseTypeName = GetFullyQualifiedTypeName(Symbol.BaseType);
                if (!string.IsNullOrEmpty(baseTypeName))
                {
                    // Put the base class before the interfaces
                    baseTypes.Insert(0, baseTypeName);
                }
            }

            // 3. Add the base types the generator needs to add
            baseTypes.AddRange(GenerateBaseTypes());
            baseTypes.AddRange(GenerateBaseInterfaces());

            if (baseTypes.Count == 0)
                return string.Empty;

            return " : " + string.Join(", ", baseTypes.Distinct());
        }

        private string GetFullyQualifiedTypeName(ITypeSymbol typeSymbol)
        {
            if (typeSymbol == null)
                return string.Empty;

            // See the implementation in Analizer.cs
            var displayFormat = new SymbolDisplayFormat(
                typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
                genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
                miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

            return typeSymbol.ToDisplayString(displayFormat);
        }

        private string FormatModifiers(string modifiers)
        {
            // Split the modifiers and process them
            var modifierList = modifiers.Split([' '], StringSplitOptions.RemoveEmptyEntries)
                .Where(m => !string.IsNullOrWhiteSpace(m))
                .Distinct()
                .ToList();

            // Remove any existing partial modifier
            bool hasPartial = modifierList.Remove("partial");

            // Sort the remaining modifiers (access modifiers first)
            var orderedModifiers = modifierList
                .OrderBy(m => m == "public" ? 0 :
                            m == "internal" ? 1 :
                            m == "protected" ? 2 :
                            m == "private" ? 3 : 4)
                .ToList();

            // If there's a partial modifier, add it last
            if (hasPartial)
            {
                orderedModifiers.Add("partial");
            }

            // Merge the modifiers, adding appropriate spaces
            return orderedModifiers.Count > 0 ? string.Join(" ", orderedModifiers) + " " : "";
        }

        public abstract bool CanWrite();
        public abstract string GetFileName();
        public abstract string[] GenerateBaseTypes();
        public abstract string[] GenerateBaseInterfaces();
        public abstract string GenerateBody();
    }
}