using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using VeloxDev.Core.Generator.Base;

namespace VeloxDev.Core.Generator.Writers
{
    public abstract class WriterBase : ICodeWriter
    {
        public const string NAMESPACE_VELOX_TIMELINE = "global::VeloxDev.Core.TimeLine";
        public const string NAMESPACE_VELOX_IMVVM = "global::VeloxDev.Core.Interfaces.MVVM";
        public const string NAMESPACE_VELOX_MVVM = "global::VeloxDev.Core.MVVM";
        public const string NAMESPACE_VELOX_AOP = "global::VeloxDev.Core.AopInterfaces";
        public const string NAMESPACE_SYSTEM_MVVM = "global::System.ComponentModel";
        public const string NAMESPACE_VELOX_IWORKFLOW = "global::VeloxDev.Core.Interfaces.WorkflowSystem";
        public const string NAMESPACE_VELOX_WORKFLOW = "global::VeloxDev.Core.WorkflowSystem";

        public ClassDeclarationSyntax? Syntax { get; protected set; }
        public INamedTypeSymbol? Symbol { get; protected set; }
        public List<ClassDeclarationSyntax>? OuterClasses { get; protected set; }

        public virtual void Initialize(ClassDeclarationSyntax classDeclaration, INamedTypeSymbol namedTypeSymbol)
        {
            Syntax = classDeclaration;
            Symbol = namedTypeSymbol;

            // 如果是嵌套类，收集外层类
            OuterClasses = [];
            var parent = classDeclaration.Parent;
            while (parent is ClassDeclarationSyntax outerClass)
            {
                OuterClasses.Insert(0, outerClass);
                parent = parent.Parent;
            }
        }

        public virtual string Write()
        {
            if (Syntax == null || Symbol == null) return string.Empty;

            StringBuilder sourceBuilder = new();

            // 获取类型参数
            string typeParameters = GetTypeParameters();

            // 获取约束子句
            string constraints = GetConstraints();

            // 获取基类型和接口列表
            string baseTypes = GetBaseTypes();

            sourceBuilder.AppendLine("// <auto-generated>");
            sourceBuilder.AppendLine("#pragma warning disable");
            sourceBuilder.AppendLine("#nullable enable");
            sourceBuilder.AppendLine();

            // 如果不是嵌套类，或者最外层类不在命名空间中，添加命名空间
            if (OuterClasses == null || OuterClasses.Count == 0)
            {
                sourceBuilder.AppendLine($"namespace {Symbol.ContainingNamespace};");
                sourceBuilder.AppendLine();
            }

            // 如果这是嵌套类，生成外层类
            if (OuterClasses != null && OuterClasses.Count > 0)
            {
                // 从最外层类开始
                var outermostClass = OuterClasses[0];
                sourceBuilder.AppendLine($"namespace {Symbol.ContainingNamespace};");
                sourceBuilder.AppendLine();

                // 格式化修饰符，确保partial关键字位置正确
                var modifiers = FormatModifiers(outermostClass.Modifiers.ToString());
                sourceBuilder.AppendLine($"{modifiers}class {outermostClass.Identifier.Text}");
                sourceBuilder.AppendLine("{");

                // 生成内层类
                for (int i = 1; i < OuterClasses.Count; i++)
                {
                    var outerClass = OuterClasses[i];
                    modifiers = FormatModifiers(outerClass.Modifiers.ToString());
                    sourceBuilder.AppendLine($"{modifiers}class {outerClass.Identifier.Text}");
                    sourceBuilder.AppendLine("{");
                }
            }

            // 生成当前类的声明
            var currentModifiers = FormatModifiers(Syntax.Modifiers.ToString());
            sourceBuilder.AppendLine($"{currentModifiers}class {Syntax.Identifier.Text}{typeParameters}{baseTypes}{constraints}");
            sourceBuilder.AppendLine("{");
            sourceBuilder.AppendLine(GenerateBody());
            sourceBuilder.AppendLine("}");

            // 关闭所有外层类（如果是嵌套类）
            if (OuterClasses != null && OuterClasses.Count > 0)
            {
                for (int i = 0; i < OuterClasses.Count; i++)
                {
                    sourceBuilder.AppendLine("}");
                }
            }

            return sourceBuilder.ToString();
        }

        private string GetTypeParameters()
        {
            if (Syntax?.TypeParameterList == null)
                return string.Empty;

            return $"<{string.Join(", ", Syntax.TypeParameterList.Parameters.Select(p => p.ToString()))}>";
        }

        private string GetConstraints()
        {
            if (Syntax?.ConstraintClauses == null || !Syntax.ConstraintClauses.Any())
                return string.Empty;

            var constraints = new StringBuilder();

            foreach (var constraintClause in Syntax.ConstraintClauses)
            {
                // 直接添加完整的约束子句
                // 约束中的类型名称会在用户代码的命名空间上下文中解析
                constraints.Append(" ").Append(constraintClause.ToString());
            }

            return constraints.ToString();
        }

        private string GetBaseTypes()
        {
            if (Symbol == null)
                return string.Empty;

            var baseTypes = new List<string>();

            // 1. 添加原始类的基类型和接口（从语义模型中获取完全限定名）
            if (Symbol.Interfaces.Length > 0)
            {
                // 获取所有接口的完全限定名
                foreach (var interfaceSymbol in Symbol.Interfaces)
                {
                    string fullName = GetFullyQualifiedTypeName(interfaceSymbol);
                    if (!string.IsNullOrEmpty(fullName))
                    {
                        baseTypes.Add(fullName);
                    }
                }
            }

            // 2. 添加基类（如果有）
            if (Symbol.BaseType != null && Symbol.BaseType.SpecialType != SpecialType.System_Object)
            {
                string baseTypeName = GetFullyQualifiedTypeName(Symbol.BaseType);
                if (!string.IsNullOrEmpty(baseTypeName))
                {
                    // 将基类放在接口之前
                    baseTypes.Insert(0, baseTypeName);
                }
            }

            // 3. 添加生成器需要添加的基类型
            baseTypes.AddRange(GenerateBaseTypes());
            baseTypes.AddRange(GenerateBaseInterfaces());

            if (baseTypes.Count == 0)
                return string.Empty;

            return " : " + string.Join(", ", baseTypes.Distinct());
        }

        private string GetFullyQualifiedTypeName(ITypeSymbol typeSymbol)
        {
            if (typeSymbol == null)
                return string.Empty;

            // 参考 Analizer.cs 中的实现
            var displayFormat = new SymbolDisplayFormat(
                typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
                genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
                miscellaneousOptions: SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

            return typeSymbol.ToDisplayString(displayFormat);
        }

        private string FormatModifiers(string modifiers)
        {
            // 分割修饰符并处理
            var modifierList = modifiers.Split([' '], StringSplitOptions.RemoveEmptyEntries)
                .Where(m => !string.IsNullOrWhiteSpace(m))
                .Distinct()
                .ToList();

            // 移除现有的partial修饰符
            bool hasPartial = modifierList.Remove("partial");

            // 排序剩余修饰符（访问修饰符优先）
            var orderedModifiers = modifierList
                .OrderBy(m => m == "public" ? 0 :
                            m == "internal" ? 1 :
                            m == "protected" ? 2 :
                            m == "private" ? 3 : 4)
                .ToList();

            // 如果有partial，加在最后
            if (hasPartial)
            {
                orderedModifiers.Add("partial");
            }

            // 合并修饰符，添加适当空格
            return orderedModifiers.Count > 0 ? string.Join(" ", orderedModifiers) + " " : "";
        }

        public abstract bool CanWrite();
        public abstract string GetFileName();
        public abstract string[] GenerateBaseTypes();
        public abstract string[] GenerateBaseInterfaces();
        public abstract string GenerateBody();
    }
}