using Demo.ViewModels.Workflow.Helper;
using VeloxDev.AI;
using VeloxDev.Core.WorkflowSystem.CompilerEx;
using VeloxDev.MVVM;
using VeloxDev.WorkflowSystem;

namespace Demo.ViewModels;

/// <summary>
/// Python script node: the core "real computation" showcase node. It receives the upstream payload — a single
/// value on a linear chain, or a join dictionary when several inputs are wired (the engine injects a
/// <see cref="IGroupData"/>), maps it to an <c>input.json</c>, executes the <see cref="Script"/> with the
/// system Python via CliWrap, and feeds the parsed <c>output.json</c> result downstream.
/// Its input and output ports are fully dynamic — generated by <see cref="PythonPortProvider"/> so the Agent
/// can freely reshape the node's ports through <c>SetEnumSlotCollection</c>.
/// </summary>
[AgentContext(AgentLanguages.Chinese, "Python 脚本节点：把上游数据（单值或汇合字典）写成 input.json，用 CliWrap 执行 Script 里的 Python 代码，读回 output.json 作为结果传给下游。输入/输出口由 PythonPortProvider 动态生成。默认大小 280×240")]
[AgentContext(AgentLanguages.English, "Python script node: writes the upstream payload (single value or joined dictionary) to input.json, executes the Python code in Script via CliWrap, and feeds the parsed output.json result downstream. Input/output ports are dynamically generated by PythonPortProvider. Default size: 280×240")]
[WorkflowBuilder.Node<PythonHelper>(workSemaphore: 1)]
public partial class PythonScriptNodeViewModel : ICompileTimeAware, IRuntimeAware
{
    public PythonScriptNodeViewModel() => InitializeWorkflow();
    // Ports are intentionally left unset here: SetSelector caches state per selector type on the same
    // enumerator, so re-setting it (e.g. the demo graph builder after the constructor) would restore the
    // stale first snapshot instead of applying the new ports. The graph builder or the Agent's
    // SetEnumSlotCollection performs the single SetSelector that materializes the ports.

    [AgentContext(AgentLanguages.Chinese, "输入口（动态，由 PythonPortProvider 生成）。用 SetEnumSlotCollection 重建：selectorTypeOrJson=PythonPortProvider 的 JSON，nonEnumTypeName='Demo.ViewModels.PythonPortProvider'")]
    [AgentContext(AgentLanguages.English, "Input slots (dynamic, generated by PythonPortProvider). Rebuild via SetEnumSlotCollection: pass the provider's JSON to 'selectorTypeOrJson' and 'Demo.ViewModels.PythonPortProvider' to 'nonEnumTypeName'.")]
    [VeloxProperty]
    [SlotSelectors(typeof(PythonPortProvider))]
    public partial SlotEnumerator<SlotViewModel> InputSlots { get; set; }

    [AgentContext(AgentLanguages.Chinese, "输出口（动态，由 PythonPortProvider 生成）。用 SetEnumSlotCollection 重建，方式同输入口")]
    [AgentContext(AgentLanguages.English, "Output slots (dynamic, generated by PythonPortProvider). Rebuild via SetEnumSlotCollection, same as the input slots.")]
    [VeloxProperty]
    [SlotSelectors(typeof(PythonPortProvider))]
    public partial SlotEnumerator<SlotViewModel> OutputSlots { get; set; }

    [AgentContext(AgentLanguages.Chinese,
        "Python 源码文本。执行契约：python <script.py> <input.json> <output.json>。脚本读 input.json：线性输入为上游产物原样；汇合输入为 {端口名: 上游产物} 字典。" +
        "脚本把结果 JSON 写入 output.json（或直接打印到 stdout）。示例：import json,sys; d=json.load(open(sys.argv[1],encoding='utf-8')); json.dump({'pass':1}, open(sys.argv[2],'w',encoding='utf-8'))。")]
    [AgentContext(AgentLanguages.English,
        "Python source text. Execution contract: python <script.py> <input.json> <output.json>. The script reads input.json: on a linear chain the upstream output is passed as-is; at a join it is a {portName: upstreamOutput} dictionary. " +
        "The script writes its result JSON to output.json (or prints it to stdout). Example: import json,sys; d=json.load(open(sys.argv[1],encoding='utf-8')); json.dump({'pass':1}, open(sys.argv[2],'w',encoding='utf-8')).")]
    [VeloxProperty] private string script = "import json, sys\n# writes result JSON to output.json (argv[2])\n";

    [AgentContext(AgentLanguages.Chinese, "标题")]
    [AgentContext(AgentLanguages.English, "Display title shown in the node header.")]
    [VeloxProperty] private string title = "Python Script";

    [AgentContext(AgentLanguages.Chinese, "Python 可执行文件（默认 python，也可填完整路径）")]
    [AgentContext(AgentLanguages.English, "Python executable (default 'python'; may be a full path).")]
    [VeloxProperty] private string pythonExecutable = "python";

    [AgentContext(AgentLanguages.Chinese, "节点作用描述：说明这个 Python 节点做什么（输入/输出、计算逻辑、用途），供 Agent 理解并在画布上展示。可用 PatchNodeProperties 修改。")]
    [AgentContext(AgentLanguages.English, "Description of what this Python node does (inputs/outputs, computation, purpose) — helps the Agent and is shown on the canvas. Editable via PatchNodeProperties.")]
    [VeloxProperty] private string description = "";

    [AgentContext(AgentLanguages.Chinese, "无状态模式下是否显示 Run/Forward 按钮")]
    [AgentContext(AgentLanguages.English, "Whether to show the Run/Forward buttons in stateless mode.")]
    [VeloxProperty] private bool showActionButtons = false;

    [VeloxProperty] private string lastStatus = "Idle";
    [VeloxProperty] private string lastRun = "-";
    [VeloxProperty] private string lastOutput = "-";

    public bool HasInputSlots => InputSlots is not null && InputSlots.Items.Count > 0;
    public bool HasOutputSlots => OutputSlots is not null && OutputSlots.Items.Count > 0;

    /// <summary>Compile-time identity injected by the compiler (Order = -1 means absolute stop).</summary>
    public ICompileContext? CompileContext { get; private set; }

    /// <summary>Whether the node is in the compile-time absolute stop state (unselected static branch / terminated).</summary>
    public bool IsCompileStopped => CompileContext is { Order: -1 };

    public void AttachCompileTimeContext(ICompileContext context)
    {
        CompileContext = context;
        LastExecutionOrder = context.Order >= 0 ? context.Order + 1 : 0;
        OnPropertyChanged(nameof(CompileContext));
        OnPropertyChanged(nameof(IsCompileStopped));
        OnPropertyChanged(nameof(HasExecutionOrder));
        OnPropertyChanged(nameof(ExecutionOrderText));
    }

    // Execution sequence number (hand-written; the generator does not cover this yet)
    private int lastExecutionOrder;
    public int LastExecutionOrder
    {
        get => lastExecutionOrder;
        set
        {
            if (lastExecutionOrder == value) return;
            lastExecutionOrder = value;
            OnPropertyChanged(nameof(LastExecutionOrder));
            OnPropertyChanged(nameof(HasExecutionOrder));
            OnPropertyChanged(nameof(ExecutionOrderText));
        }
    }
    public bool HasExecutionOrder => LastExecutionOrder > 0 || IsCompileStopped;
    public string ExecutionOrderText => IsCompileStopped ? "⊘" : LastExecutionOrder > 0 ? $"#{LastExecutionOrder}" : "-";

    /// <summary>Shared context injected at runtime (called before the engine drives this node).</summary>
    public IRuntimeContext? RuntimeContext { get; private set; }

    public void AttachRuntimeContext(IRuntimeContext context)
    {
        RuntimeContext = context;
        OnPropertyChanged(nameof(RuntimeContext));
    }
}
