using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using VeloxDev.MVVM;

namespace VeloxDev.AI.MCP;

/// <summary>
/// Bindable status view-model for a single MCP server. Follows the framework's <c>[VeloxProperty]</c>
/// MVVM conventions; property changes are broadcast by the generator via
/// <see cref="INotifyPropertyChanged"/> and can be bound directly to the UI.
/// </summary>
public partial class McpServerStatusViewModel
{
    [VeloxProperty] private string name = string.Empty;
    [VeloxProperty] private string description = string.Empty;
    [VeloxProperty] private McpServerRunMode runMode = McpServerRunMode.Npm;
    [VeloxProperty] private McpServerStatus state = McpServerStatus.NotStarted;
    [VeloxProperty] private int toolCount = 0;
    [VeloxProperty] private string? error = null;
    [VeloxProperty] private string? endpoint = null;

    /// <summary>Connected (tools available).</summary>
    public bool IsConnected => State == McpServerStatus.Connected;

    /// <summary>Installing the runtime (local npm/pip).</summary>
    public bool IsInstalling => State == McpServerStatus.Installing;

    /// <summary>Connecting (launching process / handshaking with remote).</summary>
    public bool IsConnecting => State == McpServerStatus.Connecting;

    /// <summary>Load failed (see <see cref="Error"/>).</summary>
    public bool IsError => State == McpServerStatus.Error;

    /// <summary>Chinese display text for the status (directly usable by UI / Agent).</summary>
    public string StateText => State switch
    {
        McpServerStatus.Connected => "已连接",
        McpServerStatus.Installing => "安装中",
        McpServerStatus.Connecting => "连接中",
        McpServerStatus.Error => "错误",
        _ => "未启动",
    };

    partial void OnStateChanged(McpServerStatus oldValue, McpServerStatus newValue)
    {
        OnPropertyChanged(nameof(IsConnected));
        OnPropertyChanged(nameof(IsInstalling));
        OnPropertyChanged(nameof(IsConnecting));
        OnPropertyChanged(nameof(IsError));
        OnPropertyChanged(nameof(StateText));
    }
}

/// <summary>
/// Globally bindable MCP server status view-model: the host UI binds <see cref="Servers"/> to show
/// each server's alive/installing/connecting/error status, and reads the aggregate counts
/// (<see cref="ConnectedCount"/>/<see cref="ErrorCount"/>). Held by <see cref="McpScope.Status"/>
/// and driven during <see cref="McpScope.LoadAsync"/>.
/// </summary>
public partial class McpStatusViewModel
{
    // Servers / IsLoading are generated by the generator from the [VeloxProperty] fields below
    // (do not manually declare same-named properties).
    [VeloxProperty] private ObservableCollection<McpServerStatusViewModel> servers = [];
    [VeloxProperty] private bool isLoading = false;

    /// <summary>Number of connected (alive) servers.</summary>
    public int ConnectedCount => Count(McpServerStatus.Connected);

    /// <summary>Number of failed servers.</summary>
    public int ErrorCount => Count(McpServerStatus.Error);

    /// <summary>Number of servers installing or connecting.</summary>
    public int WorkingCount => Servers.Count(s => s.State is McpServerStatus.Installing or McpServerStatus.Connecting);

    /// <summary>Whether all servers are ready (no installing/connecting/error).</summary>
    public bool IsAllReady => Servers.Count > 0 && Servers.Count == ConnectedCount;

    /// <summary>Whether at least one server has failed.</summary>
    public bool HasError => ErrorCount > 0;

    private int Count(McpServerStatus state) => Servers.Count(s => s.State == state);

    /// <summary>
    /// Registers a server and subscribes to its status changes so the aggregate counts refresh
    /// when any server changes. Should be called on the UI thread (or marshalled via
    /// <see cref="McpScope.WithSynchronizationContext"/>).
    /// </summary>
    public void Track(McpServerStatusViewModel server)
    {
        if (server is null) return;
        server.PropertyChanged += OnServerPropertyChanged;
        Servers.Add(server);
        NotifyAggregates();
    }

    /// <summary>Sets the batch-loading flag and refreshes the aggregates.</summary>
    public void SetLoading(bool loading)
    {
        IsLoading = loading;
        NotifyAggregates();
    }

    /// <summary>Clears all server status (call before reloading).</summary>
    public void Reset()
    {
        foreach (var s in Servers)
            s.PropertyChanged -= OnServerPropertyChanged;
        Servers.Clear();
        NotifyAggregates();
    }

    private void OnServerPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(McpServerStatusViewModel.State))
            NotifyAggregates();
    }

    private void NotifyAggregates()
    {
        OnPropertyChanged(nameof(ConnectedCount));
        OnPropertyChanged(nameof(ErrorCount));
        OnPropertyChanged(nameof(WorkingCount));
        OnPropertyChanged(nameof(IsAllReady));
        OnPropertyChanged(nameof(HasError));
        OnPropertyChanged(nameof(IsLoading));
    }
}
